build.xml, ivy.xml
Code that loads server extensions depends on this jar
=> add missing mina jar file

WebRoot/js/zimbraMail/share/model/ZmZimletContext.js
Fix: https://bugzilla.zimbra.com/show_bug.cgi?id=106104
=> Fix: https://bugzilla.zimbra.com/show_bug.cgi?id=106104

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties
Changes for adapting to UX review suggestions.
Changeset:
1. zm.css : Reverting change from last commit and resetting line-height style value & removing height rule.
2. skin.properties: Updating styles as per review comments.
=> ZCS-787 Universal UI: Compose fit and finish

WebRoot/js/zimbraMail/share/view/ZmAutocompleteListView.js
Fixed autocomplete widget to adopt UX changes only for email autocomplete list.
=> Autocomplete widget fix

WebRoot/css/dwt.css
Fix regression for `ZmFolderChooser` dropdown width.
=> Fix regression for `ZmFolderChooser` dropdown width.

build.xml
Updated build script to package `zm-ajax.jar` in war instead of class files
=> Updated build script to package zm-ajax.jar in war instead of class files

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/abook/Contacts.template
Changes:
* Contacts.template:
* Updated template for alphabet navigation bar
* Added/updated required CSS for `zm.css`
* Added/updated required  properties in `skin.properties`
https://jira.corp.synacor.com/browse/ZCS-1318
=> ZCS-1318: Universal UI: Contacts alphabetical navigation

WebRoot/js/zimbraMail/core/ZmZimbraMail.js
Fix condition for rendering zimlet's submenu
=> Fix condition for rendering zimlet's submenu

WebRoot/js/zimbraMail/abook/controller/ZmContactController.js, WebRoot/js/zimbraMail/core/ZmOperation.js
Description: Change in the order of toolbar items and moving tag and print operations inside action menu.
Changeset:
*  ZmContactController.js :
* Change of order of toolbar operations items.
* Overriding parent  function _getSecondaryToolBarOps to return list of operations for ActionMenu.
* ZmOperation.js :
* Adding Icons and text both visible for Cancel and Save operations on toolbar.
=> ZCS-1180 Universal UI - New / edit contact view action bar visual update

README.md
Updating the readme.md file to keep in sync with the latest repository structure and build process.
=> Updating the readme.md file to keep in sync with the latest repository structure and build process.

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties
Desc :- Styling changes for choose contact folder  dialog.
https://jira.corp.synacor.com/browse/ZCS-1222
=> ZCS-1222  Choose contact folder modal visual update

WebRoot/js/zimbraMail/tasks/view/ZmTaskMultiView.js
Changes:
* Fundamental issue is size calculations of containers while resizing. See this bug for more info: https://bugzilla.zimbra.com/show_bug.cgi?id=69593
* As part of code refactoring, updated `ZmTaskMultiView._sashCallback` method to make if more modular.
=> Task App Sash Fix

WebRoot/css/zm.css, WebRoot/js/zimbraMail/share/view/ZmListView.js, WebRoot/js/zimbraMail/tasks/view/ZmTaskListView.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties
Desc :- Update the styles, css selectors to match the styles, spacing, typography, color
for List header, headings, text, icons,task button for the task list view.
=> ZCS-1166 :- Universal UI - Task list, list view - right view

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/js/zimbraMail/prefs/view/ZmPriorityMessageFilterDialog.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
ZCS-1218 Universal UI - Active settings modal in preferences, visual update
Changeset:
* ZmPriorityMessageFilterDialog.js: Adding logic to disable "field" text based on checkbox.
* General style changes related to alignment and spacing.
=> ZCS-1218 Universal UI - Active settings modal in preferences, visual update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/tasks/view/ZmTaskListView.js, WebRoot/skins/_base/base4/skin.properties
Desc :- Changed the  underlying layout of the task list Items, to accommodate the circular progress task bar .
Changeset :-
ZmTaskListView.js :- Layout changed for list item.
zm.css :- Styles for circular progress task bar for list item.
skin.properties .
=> ZCS-1797 :- Universal UI - Integrate Progress bar with Task list, list view - right view

WebRoot/css/zm.css, WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
Description :- Changed style and layout of grant right dialog to accomodate
the design for new modal.
Changeset:-
a) skin.properties
b) Pages.template
c) ZmAccountsPages.js
=> ZCS-1225 :- Universal UI - Delegate permisions modal visual update

WebRoot/messages/ZmMsg_pt_PT.properties, build.xml
- make sure pt_PT option is shown in UI
=> ZCS-1826 [pt-PT] occurrences of Brazilian Portuguese translations in Portugal Portuguese

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/abook/Contacts.template
Updated properties view for add/edit distribution list.
https://jira.corp.synacor.com/browse/ZCS-1269
=> ZCS-1269: Universal UI- New / edit distribution list, properties view

WebRoot/messages/ZhMsg.properties, WebRoot/public/extuserprov.jsp
Changes:
* extuserprov.jsp:
* Added server-side validation check for password error
https://jira.corp.synacor.com/browse/ZCS-1727
=> ZCS-1727: External account shows 500 error when password restrictions not met

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
Updated look and feel of Preferences => Out of office interface as per new mockup.
https://jira.corp.synacor.com/browse/ZCS-1884
=> ZCS-1884: Universal UI - Out of office interface update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/mail/ZmMailApp.js, WebRoot/js/zimbraMail/mail/view/prefs/ZmSignaturesPage.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
Updated look and feel of Preferences => Signatures interface as per new mockup.
https://jira.corp.synacor.com/browse/ZCS-1211
=> ZCS-1211: Universal UI - Reorganized signature interface

WebRoot/js/zimbraMail/prefs/view/ZmSharingPage.js
ZCS-1888 Universal UI: Sharing preference interface update
ChangeSet:
ZmSharingPage.js: Adding class “ZOptionsItemsListView” to Sharing section tables (Widget ZmSharingListView)  for Preferences.
=> ZCS-1888 Universal UI: Sharing preference interface update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/mail/view/prefs/ZmMailPrefsPage.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
Desc:- Changes for Pref Mail interface  as per  mock up.
Chaged files :-
1. zm.css
2. skin.properties
3. Pages.template
4. ZmMailPrefsPage.js
=> ZCS-1891 :- Universal UI: Mail interface update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/prefs/view/ZmImportExportPage.js, WebRoot/js/zimbraMail/share/view/ZmExportView.js, WebRoot/js/zimbraMail/share/view/ZmImportExportBaseView.js, WebRoot/js/zimbraMail/share/view/ZmImportView.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/data/ImportExport.template
Updated look and feel of Preferences => Import/Export interface as per new mockup.
https://jira.corp.synacor.com/browse/ZCS-1885
=> ZCS-1885: Universal UI - Import/Export interface update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/prefs/view/ZmFilterRuleDialog.js, WebRoot/messages/ZmMsg.properties, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
Desc :- Filter Rule dialog related changes. Code changes to match the layout changes as per mock .
Changeset :-
WebRoot/css/zm.css
WebRoot/js/zimbraMail/prefs/view/ZmFilterRuleDialog.js
WebRoot/messages/ZmMsg.properties
WebRoot/skins/_base/base4/skin.properties
WebRoot/templates/prefs/Pages.template
=> ZCS-1219 :- Universal UI - Add filters modal, visual update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/abook/view/ZmContactQuickAddDialog.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/abook/Contacts.template
Updated look and feel of Quick Add Contact dialog
https://jira.corp.synacor.com/browse/ZCS-2423
=> ZCS-2423: Universal UI- Quick Add Contact Dialog

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/prefs/Pages.template
Summary of Changes:
* Updated offline settings dialog as per new mockup
https://jira.corp.synacor.com/browse/ZCS-2166
=> ZCS-2166: Universal UI - Offline Views

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.css
Description: Fixing alignment issues for the inline buttons in the dialog.
Changeset:
* zm.css: Matching font size for button text with the dialog content.
* skin.css: Aligning inline button in dialog with the dialog content.
=> ZCS-2449: Universal UI - Folder Properties Dialog

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/js/zimbraMail/share/view/dialog/ZmNewOrganizerDialog.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/share/Dialogs.template
- make name field take full width
- fix right padding for select list
- fix checkbox positioning for feed field
=> ZCS-2415 Universal UI: Add New Calendar dialog

WebRoot/css/zm.css, WebRoot/js/zimbraMail/calendar/view/ZmApptRecurDialog.js, WebRoot/js/zimbraMail/calendar/view/ZmCalItemEditView.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties
Summary of Changes:
* Updated look and feel of custom repeat dialog as per mockup
https://jira.corp.synacor.com/browse/ZCS-2416
=> ZCS-2416: Universal UI- Appointment create - Custom Repeat Dialog

WebRoot/css/zm.css, WebRoot/js/zimbraMail/calendar/model/ZmAppt.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/calendar/Appointment.template
Summary of Changes:
* Updated look and feel of calendar appointment tooltip as per new mockup
https://jira.corp.synacor.com/browse/ZCS-2412
=> ZCS-2412: Universal UI- Calendar Appointment tooltip

WebRoot/css/dwt.css, WebRoot/skins/_base/base4/skin.properties
Fixing alignment issue for week numbers:
Adding padding around menu as a calendar.
=> Fixing alignment issues for mini calendar & calendar as a menu.

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/calendar/Appointment.template
- UI changes for suggestion preference dialog
=> ZCS-2595 Universal UI: Suggestion Preference Dialog

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/js/zimbraMail/calendar/view/ZmCalPrintDialog.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/calendar/Calendar.template
Changes in alignment and spacing for consistent UI in the app.
=> ZCS-1226 Universal UI - Print calendar modal visual update

WebRoot/css/zm.css, WebRoot/js/zimbraMail/calendar/view/ZmLocationSuggestionView.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/calendar/Appointment.template
Summary of Changes:
* Updated look and feel of new calendar appointment suggest time right sidebar
Changes:
* Added updated required CSS and rules in `skin.css`, `zm.css` and `skin.properties`
https://jira.corp.synacor.com/browse/ZCS-2665
=> ZCS-2665: Universal UI - Fit and finish on appointment right sidebar suggest location interface

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/js/zimbraMail/share/view/dialog/ZmDialog.js, WebRoot/js/zimbraMail/share/view/dialog/ZmNewOrganizerDialog.js, WebRoot/js/zimbraMail/share/view/dialog/ZmNewTagDialog.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/share/Dialogs.template, WebRoot/templates/share/Widgets.template
Updated look and feel of Create New Folder dialog as per mockup.
Changes:
* Added/updated required styles in `dwt.css`, `zm.css` and `skin.css`
* Added/updated required properties in `skin.properties`
* Added/updated templates as per requirement in `Dialogs.templates` and `Widgets.template`
* Added/updated required classes for various controls in `ZmDialog.js`, `ZmNewOrganizerDialog.js` and `ZmNewTagDialog.js`
https://jira.corp.synacor.com/browse/ZCS-2432
=> ZCS-2432: Universal UI - Create New Folder Dialog

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties
Resolved issue of print calendar list issue in firefox
=> Firefox print calendar list issue:

WebRoot/public/extuserprov.jsp, WebRoot/public/login.jsp
- UI changes for external authentication screen
- fix issue in login screen where error message was not displaying in case of SSO
=> ZCS-2425 Universal UI: Authentication screen for external account when folder is shared

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/js/zimbraMail/calendar/view/ZmAttendeePicker.js, WebRoot/messages/ZmMsg.properties, WebRoot/skins/_base/base4/skin.properties
Updated look and feel of find location and find equipment dialog
Changes:
* Added/updated required styles in `dwt.css` and `zm.css`
* Added/updated required properties in `skin.properties` and `ZmMsg.properties`
* ZmAttendeePicker.js:
* Added `className` property for dialog
* Updated height of chooser list view
* Updated template of dialog
* Removed feature of allow multiple/single selection and it’s related methods for find locations dialog
https://jira.corp.synacor.com/browse/ZCS-2600 and https://jira.corp.synacor.com/browse/ZCS-2618
=> ZCS-2600 and ZCS-2618: Find Locations and find equipment dialog

WebRoot/js/zimbraMail/prefs/view/ZmSharingPage.js
- Before creating select options check if feature is disabled or not
=> ZCS-2716 Under Preferences->Sharing, Share dropdown shows 'briefcase' even if briefcase feature is disabled

WebRoot/css/dwt.css, WebRoot/js/zimbraMail/mail/ZmMailApp.js, WebRoot/js/zimbraMail/mail/controller/ZmComposeController.js, WebRoot/skins/_base/base4/skin.css, WebRoot/templates/share/Dialogs.template
Updated look and feel of mail send later dialog as per mockup
https://jira.corp.synacor.com/browse/ZCS-2426
=> ZCS-2426: Universal UI- Mail Send Later Dialog

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/js/zimbraMail/share/view/ZmShareReply.js, WebRoot/js/zimbraMail/share/view/dialog/ZmDeclineShareDialog.js, WebRoot/messages/ZmMsg.properties, WebRoot/skins/_base/base4/skin.properties
Updated look and feel of decline share dialog as per mockup
https://jira.corp.synacor.com/browse/ZCS-2446
=> ZCS-2446: Universal UI- Decline Share Dialog

WebRoot/css/dwt.css, WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/mail/Message.template
Updated look and feel of redirect mail dialog as per mockup
https://jira.corp.synacor.com/browse/ZCS-2448
=> ZCS-2448: Universal UI- Redirect email dialog

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
Bugzilla ticket: https://bugzilla.zimbra.com/show_bug.cgi?id=97460
https://jira.corp.synacor.com/browse/ZCS-1278
=> ZCS-1278: Need visual cue and hyperlink for url links during composing message

WebRoot/css/dwt.css, WebRoot/js/zimbraMail/share/view/ZmColorMenu.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/dwt/Widgets.template
Updated look and feel of color picker widget as per mockup
https://jira.corp.synacor.com/browse/ZCS-2424
=> ZCS-2424: Universal UI- Color picker widget

WebRoot/css/zm.css, WebRoot/js/zimbraMail/prefs/view/ZmShortcutsPage.js, WebRoot/skins/_base/base4/skin.properties
- change styling of shortcuts panel as per mockup
=> ZCS-2419 Universal UI: Keyboard Shortcut dialog from user menu

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties, WebRoot/svg/zimbra/ImgNewAppointment.svg, WebRoot/svg/zimbra/ImgNewTaskList.svg
- Change default color of svg icons
- remove default color applied to specific icons, which is coming now from default style for all icons
- add new appointment and new task icons
=> ZCS-2574 Universal UI: Change default colors for svg icons

WebRoot/css/zm.css, WebRoot/js/zimbraMail/share/view/dialog/ZmSharePropsDialog.js, WebRoot/skins/_base/base4/skin.css, WebRoot/skins/_base/base4/skin.properties
Updated look and feel of share folder dialog as per mockup
Changes:
* ZmSharePropsDialog.js:
*  Replaced `DwtGrouper` widget with `DwtComposite` widgets.
* Updated templates to make it consistent.
* Added/updated required styles in `skin.css` and `zm.css`
* Added/updated required properties in `skin.properties`
https://jira.corp.synacor.com/browse/ZCS-2418
=> ZCS-2418: Universal UI- Share folder dialog

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties
https://jira.corp.synacor.com/browse/ZCS-3512
=> ZCS-3512: Universal UI- Revoke share dialog size is changing to accommodate Note.

WebRoot/templates/calendar/Calendar.template
https://jira.corp.synacor.com/browse/ZCS-3294
=> ZCS-3294: Universal UI- Calendar list goes out of bounds for 'Print Calendar Dialog in firefox browser

WebRoot/js/zimbraMail/mail/controller/ZmMailListController.js
- Disable tagging functionality in separate window
=> ZCS-2919 Universal UI: Disable the 'Add New Tag' option from the new window

WebRoot/js/zimbraMail/mail/view/ZmInviteMsgView.js, WebRoot/skins/_base/base4/skin.css
- Add toolbar filler to right align propose new time button in toolbar
- Remove style which was hiding toolbar filler button
=> ZCS-3314 Universal UI: 'Propose new time' button should be aligned to right

WebRoot/skins/_base/base4/skin.css, WebRoot/svg/zimbra/ImgMeetingRequest.svg
Updated typography of mail list view as per mockup.
https://jira.corp.synacor.com/browse/ZCS-3233
=> ZCS-3233: Universal UI-  Match topography for mail list views

WebRoot/templates/calendar/Calendar.template
Fixed scroll bar issue for print calendar dialog on window's chrome
=> Fixed scroll bar issue for print calendar dialog on window's chrome

WebRoot/css/zm.css, WebRoot/js/zimbraMail/core/ZmZimbraMail.js
* Animated refresh button for some predefined time `1500ms` when refresh button is clicked.
https://jira.corp.synacor.com/browse/ZCS-633
=> ZCS-633: Universal UI- Move the refresh button to the top header

WebRoot/css/zm.css, WebRoot/js/zimbraMail/share/view/dialog/ZmDumpsterDialog.js, WebRoot/skins/_base/base4/skin.properties, WebRoot/templates/share/Widgets.template
Updated look and feel of "Recover Items" dialogs as per mockup
https://jira.corp.synacor.com/browse/ZCS-3276
=> ZCS-3276: Universal UI- 'Recover to' button is displays as if it were a header of the table on 'Recover deleted items' dialog

WebRoot/css/zm.css, WebRoot/skins/_base/base4/skin.properties
Minor alignment fixes for mail view and invite message view.
=> Minor alignment fixes for mail view and invite message view.

WebRoot/js/zimbraMail/share/view/ZmShareTreeView.js
* Added ellipsis for long folder name in find share dialog
https://jira.corp.synacor.com/browse/ZCS-3660
=> ZCS-3660: Universal UI- Scroll bar appears in the middle of the dialog when shared folder nested tree is very long

WebRoot/js/zimbraMail/mail/controller/ZmMailListController.js
8.7 patch backport for JIRA Bug ZCS-1365 - Bug 107925 - Persistent XSS - snippet [CWE-79]
=> ZCS-4115: 8.7 patch backport for JIRA Bug ZCS-1365 - Bug 107925 - Persistent XSS - snippet [CWE-79]

WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
- Sanitize href content of attachment before adding to dom
=> ZCS-3939 Bug 108786 - Persistent XSS - content-location [CWE-79]

WebRoot/js/zimbraMail/calendar/view/ZmCalColView.js
Problem : display start time of short appointment in Day View
Fix : changed to display "TIME - title" (Start time, hyphen and title)
Testing done : testing done by developer.
Link:
- RP to develop branch: https://github.com/Zimbra/zm-web-client/pull/228
Screenshot:
Before the fix:
After the fix:
=> snickers: NICPS-34: display start time of short appointment in Day View

WebRoot/js/zimbraMail/calendar/view/ZmCalItemEditView.js, build.xml
- fix done in https://github.com/Zimbra/zm-web-client/pull/244 is giving lots of regressions so for time being reverting it as it tried to solve very low severity bug which can be fixed later
=>  ZCS-4023 Fix tinymce upgrade related issues

WebRoot/js/zimbraMail/abook/view/ZmContactSplitView.js, WebRoot/js/zimbraMail/share/model/ZmObjectManager.js
- signature of ZmObjectManager.prototype.findObjects is changed so change it in all places where it is used
- define ZmObjectManager.TITLE as it was not defined
=> ZCS-4644 Bug 108902 - Persistent XSS - contact group [CWE-79]

pkg-builder.pl, scripts/postinst.sh
- Remove debug output from pkg builder command
- Removed common admin package
- All admin console related code should be part of admin console repo
=> ZCS-4465 Remove admin common package

ivy-jspc.xml
Upgraded guava jar to version 23.0
=> ZCS-4713:Upgrade guava jar

WebRoot/messages/ZhMsg.properties
=> remove zimbra Title

WebRoot/js/zimbraMail/share/model/ZmSettings.js
=> ZCS-756: Fixed typo fo ZmSetting.MAIL_ENABLED

WebRoot/js/zimbraMail/package/TinyMCE.js, WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js, WebRoot/public/templatesProxy.jsp
Based on assigned templates to the user (domain+ user), it will show the list of templates to the user
Allow the user to use templates for sending email
=> NICPS-281: Email Template - create email template zimlet part2

WebRoot/skins/_base/base3/skin.css
Fixed width issue for Login Content Box
=> NICPS-366: Regression - Login Content Box Page Width issue

pkg-builder.pl
update version no. in pkg builder script
=> NICPS-386: update version to handle zm-patch dependency

WebRoot/js/zimbraMail/package/custom.js
=> NICPS-376 : changes for login page design

WebRoot/js/zimbraMail/package/slick.js
- Dropdown not working on Redesigned Zimbra Login Page
=> NICPS-402 : Dropdown not working on Redesigned Zimbra Login Page

WebRoot/js/zimbraMail/calendar/view/ZmExternalCalendarDialog.js, WebRoot/templates/calendar/Calendar.template
It gives an option for the user to sync their Google calendars data with Zimbra
=> UI changes for Google calendar sync

WebRoot/js/zimbraMail/share/view/dialog/ZmFolderPropsDialog.js
Retention tab from Edit properties of a folder should be removed
=> NICPS-413: Modification of ZWC to remove Retention Tab for folders

WebRoot/js/zimbraMail/abook/view/ZmEditContactView.js
=> NICPS-385 : change required validation

WebRoot/skins/_base/base3/splash.html
=> NICPS-409 : Splash Screen Changes

WebRoot/skins/_base/base3/splash.html
- Fix some pointer cursor issue
=> NICPS-409 : Fix some pointer cursor issue

WebRoot/js/zimbraMail/share/controller/ZmImportExportController.js
- Sanitize file name before passing it to notification toast
=> ZCS-5625 Bug 109018 - Non-Persistent XSS - Web Client (Pref) [CWE-79]

WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
- Try to fix Random disappearance of text in the email body after clicking on send
=> ZBUG-179 text vanished after reply to email

WebRoot/skins/_base/base3/splash.html
- Splash Screen Should not appear on every refresh
=> NICPS-439 : Splash Screen Should not appear on every refresh

WebRoot/skins/_base/base3/splash.html
=> NICPS-451 : Fix Splash Screen bugs

WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
=> NICPS-458: Reverting the changes

WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
- Remove the option to remove an attachment
=> NICPS-446 : Remove the option to remove an attachment

WebRoot/js/zimbraMail/mail/view/ZmConvView2.js, WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
-  Received Date and Time should be shown in the reading pane
=> NICPS-445 : Received Date and Time should be shown in the reading pane

WebRoot/js/zimbraMail/core/ZmZimbraMail.js, WebRoot/skins/_base/base3/splash.html
=> NICPS-451 : fix space issue for counter

WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js, WebRoot/templates/prefs/Pages.template
Made changes for removing FROM label and display name for persona and external account
=> NICPS-478: Made changes for removing FROM label and display name

WebRoot/public/launchZCS.jsp
- changes for overriding user pref by login page lang
=> NICPS-468 : changes for overriding user pref by login page lang

WebRoot/public/launchZCS.jsp
=> NICPS-468 : revert changes

WebRoot/WEB-INF/tags/infra/view.tag
=> NICPS-396: Remove help link

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
=> NICPS-480 : Saving signature Error

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
=> NICPS-470: Fixed editor formatting issue

WebRoot/js/zimbraMail/share/view/ZmSearchToolBar.js
NICPS-399 : Add space to the text while performing the folder search.
=> NICPS-399 : Add space to the text while performing the folder search.

WebRoot/js/zimbraMail/share/controller/ZmSearchController.js, WebRoot/js/zimbraMail/share/view/ZmSearchResultsToolBar.js, WebRoot/js/zimbraMail/share/view/ZmSearchToolBar.js
NICPS-516 : Language translation in search bar
=> NICPS-516 : Language translation in search bar

WebRoot/js/zimbraMail/mail/ZmMailApp.js, WebRoot/templates/prefs/Pages.template
NICPS-540: Changes in Account Tab from preferences
=> NICPS-540: Changes in Account Tab from preferences

WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js, WebRoot/js/zimbraMail/core/ZmRequestMgr.js
Major parts of the development was done in ZCS-5836.
There are some technical corrections required to be
attended here.
Adding necessry params while creating HAB overview.
=> ZCS-5418 : Adding HAB Tree related improvements.

WebRoot/m/zmain
Fixed wrong URL issue in Mobile version
=> NICPS-428: Fixed wrong url issue

WebRoot/js/zimbraMail/share/controller/ZmSearchController.js, WebRoot/js/zimbraMail/share/view/ZmSearchToolBar.js
NICPS-558: Advance Search Issue with 2040 build
=> NICPS-558: Advance Search Issue with 2040 build

WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js, WebRoot/js/zimbraMail/core/ZmRequestMgr.js, WebRoot/js/zimbraMail/share/model/ZmSettings.js, WebRoot/templates/abook/Contacts.template
HAB tree structure is rendering according to logged in domain. Also long HAB group names and the group nested too down in the hierarchy is visible now through scrolling.
=> ZCS-6720 HAB tree structure for non default domain

WebRoot/WEB-INF/tags/message/messagePrintView.tag
NICPS-543: Print Time and Mail Receiving Time is different
=> NICPS-543: Print Time and Mail Receiving Time is different

WebRoot/js/zimbraMail/calendar/view/ZmCalItemEditView.js, WebRoot/js/zimbraMail/prefs/view/ZmNotificationsPage.js
NICPS-576: Validation check in preference notification by email
=> NICPS-576: Domain name should not display in status

WebRoot/public/launchZCS.jsp
Fixed zimbra text display issue in the browser tab
When language is different than en, hi, ta, then Zimbra labels show
=> NICPS-569: Fixed zimbra text display issue in header tab

WebRoot/js/zimbraMail/prefs/controller/ZmPrefController.js
NICPS-575: Validation check in preference notification by email
=> NICPS-575: Validation check in preference notification by email

WebRoot/WEB-INF/tags/mobile/moDisplayAppointment.tag, WebRoot/WEB-INF/tags/mobile/moFolderForm.tag, WebRoot/h/printappointments
Have made a single PR for ZBUG-883,ZBUG-884,ZBUG-885
=> ZBUG-883:  Persistent XSS - Mobile Web Client

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
NICPS-577: Fix issue of blank text in Edge browser
=> NICPS-577: Fix issue of blank text in Edge browser

WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js
Some pagination related props were not handled properly.
Using pagination props received in response properly.
=> ZCS-7264 : Fixing missing Dl-member issue.

WebRoot/h/options
Added LDAP attribute condition in HTML mode to show Account section
=> NICPS-611: Added condition to show account section or not

WebRoot/js/zimbraMail/prefs/view/ZmNotificationsPage.js
NICPS-609: Issues with Calendar to SMS notification preferencess
=> NICPS-609: Issues with Calendar to SMS notification preferencess

WebRoot/skins/_base/base3/skin.css, WebRoot/skins/_base/base3/splash.html
Added location message on splash screen and fixed css
=> NICPS-624: Updated css for splash screen

WebRoot/js/zimbraMail/share/ZmUploadManager.js, WebRoot/js/zimbraMail/share/view/dialog/ZmUploadDialog.js
NICPS-629: Issue with attachment in Signature
=> NICPS-629: Issue with attachment in Signature

WebRoot/js/zimbraMail/mail/ZmMailApp.js
NICPS-627: Account Tab preference default value change
=> NICPS-627: Account Tab preference default value change

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
NICPS-628: Compose screen Typing Help & Font issue
=> NICPS-628: Compose screen Typing Help & Font issue

WebRoot/public/historyProxy.jsp
Fix production login history and splash screen issue
=> NICPS-654: Fix production login hhistory zimlet issue

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
Add odia language option in compose screen
=> NICPS-660: Add odia language option

WebRoot/js/zimbraMail/mail/controller/ZmMailListController.js
Add alert popup/dialog model to confirm mails to spam folder
=> NICPS-670: Add alert popup for spam move mail

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
=> NICPS-674: Fix odia language translation

WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js
Remove gov.in.local domain users from list
=> NICPS-672: Remove gov.in.local domain users from list

WebRoot/skins/_base/base3/splash.html
Add jquery ajax request with timeout option
=> NICPS-677: Add ajax request with timeout

WebRoot/skins/_base/base3/splash.html
=> NICPS-686: Fix js error issue

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
Add language labels in own language
=> NICPS-684: Added language labels

WebRoot/js/zimbraMail/share/view/ZmAddressInputField.js
Fix calendar close issue when open trough contact popup
=> NICPS-689: fix calendar close issue

WebRoot/WEB-INF/tags/options/optAccounts.tag, WebRoot/h/options
Removed gov.in.local alias in html
=> NICPS-694: Remove gov.in.local alias in html

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
Fix hindi undefined translation
=> NiCPS-693: Fix hindi undefined translation

WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
=> NICPS-709: Fix pramukhime js error

WebRoot/h/options
fix html mode shortcut tab issue
=> NICPS-710: fix html mode shortcut tab issue

WebRoot/js/zimbraMail/share/controller/ZmActionController.js, WebRoot/js/zimbraMail/share/model/ZmList.js
NICPS-695: Spam filter issue while undo the marked mail
=> NICPS-695: Spam filter issue while undo the marked mail

WebRoot/js/zimbraMail/core/ZmZimbraMail.js
Stop modify pref request for language option
=> NICPS-721: Stop modify pref request for language option

WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
Web client is not rendering full html content
=> ZCS-8165 : Web client is not rendering full html content

WebRoot/css/login.css, WebRoot/public/error.jsp, WebRoot/templates/share/Dialogs.template
reskin of error.jsp page and removing zimbra url from 2fa and forgort-password flow and url for the login page can be cusotomised in WebRoot/skins/harmony/skin.properties
=> PREAPPS-4347 :  Reskin of error.jsp and remove of url from 2fa and forgetpassword flow

WebRoot/public/login.jsp, ivy-jspc.xml
=> ZCS-9598:- Added code to support password rules while doing force change password after first login.

WebRoot/messages/ZmMsg_ro.properties
Fixed translations for Romanian language
=> ZCS-10076: User unable to use Romanian Language and Port Localisation changes

WebRoot/h/changepass
BlockCommonPassword was wrongly handled in change-password jsp template.
Fixing the same by using boolean value instead of numbers.
=> ZCS-10230 : Fixing blockCommonPassword handling.

WebRoot/skins/_base/base3/skin.css
Making sure there is scroll bar when change password box is larger than available height.
Using scrollbar in smaller screen.
=> ZBUG-2044 : Handle smaller screen for change password screen.

WebRoot/WEB-INF/tags/autoComplete.tag, WebRoot/WEB-INF/tags/compose/yuiInclude.tag, WebRoot/WEB-INF/tags/conv/convColumnView.tag, WebRoot/WEB-INF/tags/conv/convListView.tag, WebRoot/WEB-INF/tags/conv/convRowView.tag, WebRoot/WEB-INF/tags/head.tag, WebRoot/WEB-INF/tags/keyboard.tag, WebRoot/WEB-INF/tags/message/messageColumnView.tag, WebRoot/WEB-INF/tags/message/messageListView.tag, WebRoot/WEB-INF/tags/message/messageRowView.tag, WebRoot/WEB-INF/tags/mobile/moAutoComplete.tag, WebRoot/WEB-INF/tags/rest/restSpreadsheetView.tag, build.xml
Backport the change on ZCS-8441 to 8.8.15 patch. Target branch is `hotfix/8.8.15.p31`.
Original PR: https://github.com/Zimbra/zm-web-client/pull/636
Related PR: https://github.com/Zimbra/zm-admin-console/pull/100
=> ZCS-8441 : Updated yui 2.5.1 to 2.9.0

WebRoot/public/Docs.jsp, WebRoot/public/proto/index.jsp
- Fix condition which was wrongly implemented in https://github.com/Zimbra/zm-web-client/pull/481
=> ZCS-11183 Fix condition

WebRoot/public/Docs.jsp, WebRoot/public/error.jsp, WebRoot/public/proto/index.jsp
- Also partially cherry-pick https://github.com/Zimbra/zm-web-client/commit/5bdd88797e6a84447cfd691f70bb985ded685a99
=> ZCS-11183 Cherry-pick changes from develop branch

WebRoot/js/zimbraMail/briefcase/controller/ZmBriefcaseController.js
- Remove selection of item, if user has uploaded new version of any selected item OR user has performed check-in/checkout operation on selected item.
=> ZCS-11673: Selected briefcase item get unselected when user set/unset Tag.

WebRoot/js/zimbraMail/core/ZmOperation.js, WebRoot/js/zimbraMail/share/model/ZmKeyMap.js
- Show given text as label if key not present in ZmMsg.
- Allow to inherit ZmKeyMap function.
=> ZCS-11865: Classic UI - Zimlet for Doc Editing

build.xml, ivy.xml
Updated jaxws-rt version to 4.0.0
=> ZBUG-2998: Updated jaxws-rt version to 4.0.0

WebRoot/messages/ZmMsg.properties
Added missing key in property file for _splashScreenSwitch_
=> ZCS-12388: Added missing key in property file

WebRoot/WEB-INF/tags/calendar/calendarUrl.tag, WebRoot/WEB-INF/tags/img.tag, WebRoot/WEB-INF/tags/message/body.tag, WebRoot/WEB-INF/tags/message/displayMessage.tag, WebRoot/WEB-INF/tags/message/messagePrintView.tag, WebRoot/WEB-INF/tags/rest/restCalendarUrl.tag
Reference: 
* ZCS-11198: https://github.com/Zimbra/zm-web-client/pull/689
* ZCS-11201: https://github.com/Zimbra/zm-web-client/pull/690
* ZCS-11202: https://github.com/Zimbra/zm-web-client/pull/707
* ZCS-11204: https://github.com/Zimbra/zm-web-client/pull/694
=> ZCS-12672, ZCS-12674: fixing sanitization

WebRoot/js/zimbraMail/briefcase/view/ZmDetailListView.js, WebRoot/js/zimbraMail/calendar/view/ZmLocationSuggestionView.js
Handling aria-label for briefcase folder and tab navigation on location suggestion view.
See the changes of zm-ajax: https://github.com/Zimbra/zm-ajax/pull/115
=> ZCS-12684 Fix application issue as per automation results

WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js, WebRoot/js/zimbraMail/share/view/ZmAppChooser.js, WebRoot/templates/share/Widgets.template
- In the app tab navigation, Assigned heading role to parent element of tab button.
- Fixed missing heading on preference page.
=> ZCS-12697 Investigate and fix WCAG heading issue recognized by NVDA tool

Dockerfile, WebRoot/public/login.jsp
Updated Dockerfile
- Modifying login.jsp file at build time to provide option on login page to choose classic or modern client on kubernetes setup
=> ZCS-12886 Make changes on classic ui login.jsp file

WebRoot/public/login.jsp
Add condition check before redirecting to zimbraWebClientLoginURL or zimbraWebClientLogoutURL.
=> ZCS-12872: added condition check for login and logout URL redirection

WebRoot/templates/calendar/Appointment.template, WebRoot/templates/calendar/Calendar.template, WebRoot/templates/data/ImportExport.template, WebRoot/templates/dwt/Widgets.template, WebRoot/templates/mail/Message.template, WebRoot/templates/prefs/Options.template, WebRoot/templates/prefs/Pages.template, WebRoot/templates/share/App.template, WebRoot/templates/share/Dialogs.template
- because of usage of div as self closing tag, issue was coming in testcafe
=> ZCS-13040 div is non self closing tag

WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js, WebRoot/js/zimbraMail/share/view/ZmDesktopAlert.js
adding notifyZimlets for customization.
=> ZCS-12968: added notifyZimlets

WebRoot/WEB-INF/tags/infra/skin.tag, WebRoot/public/error.jsp
- error.jsp was doing unnecessary validation instead same thing can be handled by skin.tag
=> ZCS-12944 Validation of skin parameter is moved to skin.tag

WebRoot/css/zm.css, WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js, WebRoot/js/zimbraMail/prefs/view/ZmMobileDevicesPage.js, WebRoot/js/zimbraMail/prefs/view/ZmSharingPage.js, WebRoot/js/zimbraMail/prefs/view/ZmZimletsPage.js, WebRoot/skins/_base/base3/zhtml.css, WebRoot/templates/prefs/Pages.template
Added caption on the UI table and screenreader table.
See the changes of zm-ajax: https://github.com/Zimbra/zm-ajax/pull/122
=> ZCS-13075 WCAG Re-opened Issues Part 5

.github/CODEOWNERS, WebRoot/public/extuserprov.jsp, WebRoot/skins/_base/base3/skin.css
- login page was having older css and hence it was not aligning properly
=> ZCS-13307 Fix layout of external user registration page

WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
adding notifyZimlets for customization.
=> ZCS-13507: added notifyZimlets

WebRoot/m/momoveto
=> ZBUG-3490: XSS in /m/momoveto via st
