- WebRoot/js/zimbraMail/abook/model/ZmContact.js
- WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js
- WebRoot/js/zimbraMail/offline/ZmOffline.js
Changes:
* Updated all GetContactsRequest API to include flag `returnCertInfo = 1`
* Following files are updated:
* ZmContacts.js
* ZmContactPicker.js
* ZmOffline.js
https://jira.corp.synacor.com/browse/ZCS-999
https://jira.corp.synacor.com/browse/ZCS-991
> ZCS-999: Send returnCertInfo Flag to Server in GetContactRequest API

- WebRoot/css/dwt.css
- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js
- WebRoot/js/zimbraMail/calendar/view/ZmReminderDialog.js
- WebRoot/js/zimbraMail/mail/controller/ZmComposeController.js
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/dwt/Widgets.template
- WebRoot/templates/zimbra/Widgets.template
Changes:
* ZmReminderDialog.js:
* Removed reference to separator elements as per changes in template files.
* ZmContactPicker.js:
* Removed reference to separator elements as per changes in template files.
* ZmComposeController.js:
* Updated dialog for `Save as Draft` as per mockup
* Updated templates file `dwt/Widgets.template` and `zimbra/Widgets.template` as per requirement
* Updated required css for `dwt.css`, `zm.css` and `skin.css`
* Updated required properties in `skin.properties`
https://jira.corp.synacor.com/browse/ZCS-913
> ZCS-913- Universal UI: Standard modal style changes

- WebRoot/css/zm.css
- WebRoot/skins/_base/base4/skin.properties
Changes:
* zm.css: Moved out style of pain-text editor into property variable
* skin.properties: Added property for plain-text editor file
https://jira.corp.synacor.com/browse/ZCS-787
> ZCS-787 Compose Fit & Finish

- WebRoot/skins/_base/base4/skin.properties
Updated skin.property variable name from `AddressBubbleBgActive ` to `AddressBubbleActive `, as `AddressBubbleBgActive ` variable is no longer exists.
> Address bubble regression fix for mail search sidebar

- WebRoot/skins/_base/base4/skin.properties
Fix issue of address bubble and tag bubble in mail view reading pane.
Before:
After fix:
> Fix issue of address bubble and tag bubble in mail view reading pane.

- WebRoot/js/zimbraMail/share/view/ZmTagMenu.js
- WebRoot/messages/ZmMsg.properties
ZCS-901: Universal UI: Modernize the style of the actions menu tag dropdown
Changeset:
1. ZmMsg.properties:
* Removing obsolete property removeTag.
* Updating allTags property value.
2. ZmTagMenu.js:
* Simplifying the tags menu: All tags in single list and showing added tags with a checkmark.
* Removing code for remove tag menu.
* Removing menu item remove tag ( when only 1 tag added).
> ZCS-901: Universal UI: Modernize the style of the actions menu tag dropdown

- WebRoot/skins/_base/base4/skin.properties
* Updated `hexToRGBA` call with `lighten` for container elements.
* Changed background color for main container to `AppBg`
https://jira.corp.synacor.com/browse/ZCS-1329
> Removed background fluctuations while dragging sash

- WebRoot/skins/_base/base4/skin.properties
ZCS-1032 Universal UI: Mini Calendar prev/next month buttons changing Years not the months.
Issue: Button width for calendar header changing on hover, causing the buttons to move on hover in the UI.
Fix: Extra border was getting applied in hover state , affecting the bounding box .
Change set:
1. Skin.properties: Removing extra border applied on hover for buttons on mini cal to have a same styling on hover and non hover states.
> ZCS-1032 Universal UI: Mini Calendar prev/next month buttons changing Years not the months.

- WebRoot/css/dwt.css
- WebRoot/skins/_base/base4/skin.properties
Reason: Due to outline, we have to keep 1px breathing space around some of the elements, as outline adds-up in box-model sizing. In this case, element do not has focus, 1px breathing space around area continues to shows up.  
This may-not be final style for focus state of an elements, but just a better approach so that we don't end up adding 1px space around form some elements.
> Changed style for focus state of an element from outline to box-shadow

- WebRoot/css/common.css
- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/briefcase/view/ZmBriefcaseIconView.js
- WebRoot/js/zimbraMail/briefcase/view/dialog/ZmBriefcaseTabView.js
- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.properties
Changeset:
1. Moving svg coloring styles from zm.css to skin.css to keep all similar styles at one place.
2. ZmBriefcaseTabView.js: Updating the dialog with from 500 to 600.
3. ZmBriefcaseIconView: Getting icon using AjxImg utility.
4. zm.css & skin.css : Adding styles for briefcase row item as per UX mockups.
> ZCS-912 Universal UI: Attach briefcase item modal from compose view

- WebRoot/css/zm.css
- WebRoot/skins/_base/base4/skin.properties
Issue: With change in zcs-823, all fields were inheriting background color from their parent element causing issues where it is not the required behaviour (Login page for example).
Fix: Reverting the change that make this behaviour and applying the change restricting it only to the contact header screen where its required at the moment.
Changeset:
* zm.css: Adding selector to target input fields for contact edit header part.
> Fixing Background color for input fields.

- WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js
- WebRoot/templates/prefs/Pages.template
ZCS-129 Can't Disable External Imap and pop3 Access through cos and per user basis
Issue: Add external account button visible in preference section even if the related attribute is set to FALSE in ldap.
Root Cause:  ZmPreferencesPage::_isEnabled() is not passing the prefId to checkPrecondition function thus returning true always and the attribute value getting ignored.
Fix: Passing the prefId if precondition is not present which in turn checks the setting value in the ldap and returns false if it is set so.
Changeset:
* ZmPreferencesPage.js: Passing prefId if prefPrecondition is not available while calling ZmAppCtxt::checkPrecondition(). (Reverting bug:97899)
* Pages.template: Showing mail/compose/use keyboard shortcut ctrl+enter to send message all the time. Previously it used to be …
> ZCS-129 Can't Disable External Imap and pop3 Access through cos and per user basis

- WebRoot/css/zm.css
Updating the css selectors for images in choose contact folder dialog as there has been recent changes in the layout of svg image tag as part of bug ZCS-1315
> Update CSS Selectors for choose contact folder dialog images.

- WebRoot/css/dwt.css
- WebRoot/js/zimbraMail/tasks/ZmTasksApp.js
- WebRoot/js/zimbraMail/tasks/controller/ZmTaskListController.js
- WebRoot/skins/_base/base4/skin.properties
ZCS-1167 Universal UI: Task list action bar and left sidebar
Changeset:
* ZmTaskListController.js :
* Removing icons for filterby feature.
* Moving reading pane options into submenu similar to mail app.
* Moving Print & Tag toolbar options into secondary menu dropdown (actions menu).
* ZmTasksApp.js : Updating icon for complete operation.
* dwt.css : Updating selector for view button in the toolbar to make it heavier than the other selector .
* Skin.properties: Updating the drop down icon color for view button on the toolbar.
> ZCS-1167 Universal UI: Task list action bar and left sidebar

- WebRoot/js/zimbraMail/share/view/ZmAppChooser.js
ZCS-1202 Universal UI:X mark next to the application name in the "More" pull-down menu
Description: Close button getting rendered on ui in the more drop down for the default applications as well.
Expected: Close button visible only for closable applications and app views. (Prefs, new compose, task etc).
Changeset:
ZmAppChooser.js: Adding check before creating a menu item to create a close button only if the app view is not a default application.
> ZCS-1202 Universal UI:X mark next to the application name in the "More" pull-down menu	

- WebRoot/js/zimbraMail/mail/controller/ZmMailListController.js
Issue: Shortcut key “q” that triggers to have mail contents in the tooltip is not XSS safe and set’s the content without encoding.
Changeset:
* ZmMailListController.js: Html encoding the mail fragment before setting it to the ui.
> ZCS-1365: Bug 107925 - Persistent XSS - snippet [CWE-79]

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/mail/view/ZmConvView2.js
- WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
- WebRoot/js/zimbraMail/share/view/ZmSearchToolBar.js
- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/mail/Message.template
Changes:
* Message.template:
* Added new template `#CollapsedAddress ` for collapsed address view
* Updated mail header template as per requirement
* ZmMailMsgView.js:
* Updated `_renderMessageHeader` method  to add new parameters `toAddrs`, `fromAddrs` for template
* Added new method `ZmMailMsgView.prototype._setupMailAdressExpandCollapse` for expand/collapse feature
and its related methods
* ZmConvView2.js:
* Updated `ZmMailMsgCapsuleViewHeader.prototype.set` method to pass new parameters `toAddrs` and
`fromAddrs` to template and called method to collapse address header.
* Added/updated required CSS for  `skin.css`, `zm.css`
* Added/updated required strings for `skin.properties`
https://jira.corp.synacor.com/browse/ZCS-908
> ZCS-908: Universal UI- From / To expansion and collapsed interface on the inbox reading pane

- WebRoot/js/zimbraMail/prefs/controller/ZmPrefController.js
ZCS-1769 Universal UI: Preference tab sending Batch Request on each click.
Description: isAppView coming as true in the UI framework causing the Preferences app to be initialised on each click causing networks requests to be sent all again.
Fix: Setting isAppView for the preferences view as true.
Changeset:
* ZmPrefController::_setView() : Passing isAppView as true while creating a new view through AppViewManager.
> ZCS-1769 Universal UI: Preference tab sending Batch Request on each click.

- WebRoot/WEB-INF/tags/briefcase/briefcaseListViewToolbar.tag
- WebRoot/WEB-INF/tags/briefcase/newBriefCheck.tag
Issue:
- html client has jsp session timeout of 5 mins, so after that it needs to recreate jsp session based on valid authtoken but we had code that sets csrfSupported to false if request type is POST
Resolution:
- zm-taglib: ZJspSession.java, revert back change which checked request type for setting csrfSupported flag, which was done to fix https://bugzilla.zimbra.com/show_bug.cgi?id=104828 issue, I think we should blindly not consider all POST requests as CSRF vectors
- zm-web-client: newBriefCheck.tag & briefcaseListViewToolbar.tag, properly fix https://bugzilla.zimbra.com/show_bug.cgi?id=104828 by checking for valid crumb when trying to upload briefcase attachment
> ZCS-817 unexpected logout happening in html client

- WebRoot/js/zimbraMail/package/DocsPreview.js
- WebRoot/js/zimbraMail/package/Startup1_1.js
- build.xml
- ivy.xml
- use newly created resolver for zip files
- Don't package AjxTimezoneData.js file in Startup_1.1.js as it is loaded by jsp
> ZCS-1661 Fix failing build

- WebRoot/WEB-INF/tags/rest/restDocumentPreview.tag
- WebRoot/WEB-INF/tags/rest/restSlidePreview.tag
Issue:
- AjxTimezoneData.js file was removed from DocsPreview package as part of changes in https://github.com/Zimbra/zm-web-client/commit/d5ea31d2d168522a3b7a3856caed8ad782a58cab, this was done to make sure we are not packaging timezone data file and always access it through file system to make sure we take care of updates in timezone data
Resolution:
- include AjxTimezoneData.js file wherever DocsPreview package is getting included
> ZCS-1941 Exception while viewing document in Briefcase

- WebRoot/js/zimbraMail/mail/view/ZmConvListView.js
- WebRoot/js/zimbraMail/mail/view/ZmMailMsgListView.js
ZCS-1892
Universal UI: Mail with no message body shows 'ZmMailMsg' or 'ZmConv' in mail list right reading pane view.
Issue:
*  Fragment comes as undefined if there’s no mail body, presence of a condition against the fragment causing the execution to reach 	  DwtListView::_getCellContents() from where item.String() is causing item name to be returned to UI.
Fix Description:
*  Removed the condition to check presence of mail object fragment, as this._getFragmentSpan take’s care of empty/undefined fragment.
Changeset:
*  ZmConvListView.js
*  ZmMailMsgListView.js
> ZCS-1892 Universal UI: Mail with no message body shows 'ZmMailMsg' or 'ZmConv' in mail list right reading pane view.

- WebRoot/css/dwt.css
- WebRoot/skins/_base/base4/ZmSkin.js
- WebRoot/skins/_base/base4/skin.properties
ZCS-1577: UI interface shifts up when navigating to empty lists in WebClient.
Issue: There is height calculation that takes place for the list view and for Tasks & Briefcase thats dependent on the height on ListView Header height. The issue was invalid value of constant storing the height value.
Changeset:
* ZmSkin.js: Updating the value of List View header item.
* skin.properties:
* Updating height relative value to be more specific so that it resolves more close to 35px.
* Updating property to apply border-box sizing to ListView header item.
**Note:** The height for header node is set to 35px and there’s a 1px bottom border that makes it 36px and the calculations are made based on 36px height for list view.
> ZCS-1577 UI interface shifts up when navigating to empty lists in WebClient.

- WebRoot/templates/calendar/Appointment.template
Issue:
- XSS attack was possible in webclient by creating a resource with malicious name
Resolution:
- html encode resource name and description before adding it to DOM
> ZCS-1779 Persistent XSS - Resource Name field

- WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
Issue:
- For external POP/IMAP account is selected as from address and read receipt is requested then email address to send read receipt was not populating correctly
Resolution:
- in case of external account get email address from datasource instead of getting from identity
> ZCS-1874 Read Receipt is not working correctly for POP/IMAP accounts

- WebRoot/css/zm.css
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/abook/Contacts.template
Changes:
* Updated contact edit group row to show `Quick Add to Contact` button when user enters email address in textarea.
https://jira.corp.synacor.com/browse/ZCS-1897
> ZCS-1897: Width of the rows in Member list view of Contact Group is not uniform for members added from GAL and by adding email address

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
- WebRoot/messages/ZmMsg.properties
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/prefs/Pages.template
ZCS-1890 Universal UI: Account interface update
Changeset:
* zm.css: Adding style rules to target preferences sub-heading label & its content selectors. (css classesZOptionsSubHeadingLabel & ZOptionsSubHeadingContent)
* ZmAccountsPage.js:
*  Update buttons to use ZAltButton styles.
*  Update searchFolder icon to Search icon.
*  Updated button label from “Delete” to “Remove Account”
* ZmMsg.properties: Updating the strings & widths of preferences account section columns.
* skin.properties: Updating related style variables.
* Pages.template: Updating template for layout changes & adding css classes for subheadings.
> ZCS-1890 Universal UI: Account interface update

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js
- WebRoot/skins/_base/base4/skin.properties
Fix:
* Added new class `ZmPrefInputField` which can be applied directly to `input[type=text]` field or `DwtInputWidget` object.
* In preference section, almost all input control are created by method named `ZmPreferencesPage.prototype._setupInput`. So added this newly created class to all controls created by this method.
* In this case original class `DwtInputField` has also been kept to preserve other functionalities. (like disabled state etc.)
* In case input control is created with template, we can add class `ZmPrefInputField ` in template to retain staying.
* Tested across different preference section. Also inline inputs and other combos has no effect on this and seems to be working fine.
https://jira.corp.synacor.com/browse/ZCS-2394
> ZCS-2394: Universal UI: Match the text input width of elements in all the sections in the Preferences

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/abook/view/ZmContactSplitView.js
**Fix Description**: 
The new styling changes which includes CSS selectors were targeting elements inside the ListView (ZmContactSimpleView). In case of proxy element, there’s no context of the ListView or its classes & thus partially some rules were not getting applied on the proxy & was breaking the UI. Fix the issue by removing the scope of the list view class & depending only on the Contact row specific class “SimpleContact”.
**Changeset**:
* zm.css: Updated Row specific style selectors to not depend on the listview  class ZmContactSimpleView  but on the specific class i.e. SimpleContact only
* ZmContactSplitView.js:
*  Removing dragProxy specific logic for changing width/padding. Matching the UI element to be same as the list item element.
*  Changing the order of row class for the …
> ZCS-2450 Style the drag proxy element for Contact list

- WebRoot/css/common.css
- WebRoot/css/dwt.css
- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/share/model/ZmShare.js
- WebRoot/js/zimbraMail/share/view/ZmColorButton.js
- WebRoot/js/zimbraMail/share/view/ZmShareReply.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmFolderPropertyView.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmFolderPropsDialog.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmRevokeShareDialog.js
- WebRoot/messages/ZmMsg.properties
- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/share/Dialogs.template
**Description**: Changes to simplify the UX and match the styling as per new UX mockups.
**Changeset**:
* ZmFolderPropertyView.js:
* Removing the span for showing the folder name that cannot be edited, using disabled input field now.
* Formatting ZmMsg.offlineFolderSyncInterval to replace placeholder with the input field for offline sync interval.
* ZmShare.js:
* Adding action items for sharing: edit,revoke & resend.
* ZmColorButton.js:
* Adding class "ZSelect" to widget to make it look like DwtSelect.
* ZmFolderPropsDialog.js:
* Using new icons for the actions instead of text labels.
* skin.css:
* Adding related styles.
* Dialogs.template:
* Updating ZmFolderRetentionView dialog.
> ZCS-2449 Universal UI - Folder Properties Dialog

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/abook/view/ZmContactSearch.js
- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
- WebRoot/js/zimbraMail/mail/view/prefs/ZmSignaturesPage.js
- WebRoot/messages/ZmMsg.properties
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/abook/Contacts.template
Desc:- Changes done to the layout to adjust the look and feel as similar to mock up.
Added support for avatar image if present in contact .
Overriding the DwtListView.prototype.createHeaderHtml as we donot need a header.
Using image instead of text for search.
Added code to add classes to contact search results list cell.
Changeset :-
WebRoot/css/zm.css
WebRoot/js/zimbraMail/abook/view/ZmContactSearch.js
WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
WebRoot/js/zimbraMail/mail/view/prefs/ZmSignaturesPage.js
WebRoot/messages/ZmMsg.properties
WebRoot/skins/_base/base4/skin.properties
WebRoot/templates/abook/Contacts.template
> ZCS-1216 :- Universal UI - Browse for vcard modal, visual update

- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
- WebRoot/js/zimbraMail/share/view/ZmStatusView.js
- fix implemented in https://github.com/Zimbra/zm-web-client/commit/8426bc1a3911f4f5ea1ff319d122cc0c5c70bbe9 created a regression where adding anchor links in toast message was not working and showing html content
- encode data only when needed instead of adding fix at core level
> ZCS-2348 XSS possible in webclient using malicious account name

- WebRoot/skins/_base/base4/skin.properties
ZCS-1294  Compose view text inputs should align with the text editor in all cases.
Issue: The empty padding td at the end is taking the available space which is more in case where from drop down is not available.
Fix: Adding width as 1% to the last div that’s there for space so that it doesn’t take all available space.
Changeset:
* skin.properties:  Adding width of 1% to ComposeViewHeaderEmptyRight property variable.
> ZCS-1294:  Compose view text inputs should align with the text editor

- WebRoot/js/zimbraMail/core/ZmAppCtxt.js
- WebRoot/js/zimbraMail/core/ZmOperation.js
- WebRoot/js/zimbraMail/mail/controller/ZmMsgController.js
ZCS-2259 Universal UI: Toolbar in new-window-view-mail should match the default style.
Changeset:
* ZmApPCtxt.js: Increasing width of new window to fit the toolbar in default view.
* ZmOperation.js: Setting flags true to show icon & text both for Close operation.
* ZmMsgController.js:  Adding class ZToolbar for msg view to inherit common styling for toolbar’s.
> ZCS-2259 Universal UI: Toolbar in new-window-view-mail should match the default style 

- WebRoot/js/zimbraMail/share/view/ZmAutocompleteListView.js
- WebRoot/skins/_base/base4/skin.css
Issue:
- Height of individual tab was not propagating to the top level container
Resolution:
- Skin container was absolute positioned therefore it was not getting considered in same dom chain as the individual tabs, so it was not able to take height of individual tabs
> ZCS-2167 Missing top tabs on IE11

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/calendar/view/ZmCalMonthView.js
- WebRoot/js/zimbraMail/share/view/ZmButtonToolBar.js
- WebRoot/skins/_base/base4/skin.properties
ZCS-736 Universal UI: Calendar month view fit and finish
Changeset:
* ZmCalMonthView.js: Removing code for current month title in the Month view.
* ZmButtonToolbar.js: Adding logic for fallback of params.secondaryButtonsPosition to buttons length is position is not passed in params.
* zm.css & skin.properties: Styling changes for calendar month view.
**NOTE:** : Styling changes have been done in zm.css and not created separate property variables to make it customisable at this moment. Reason being there are other related component style rules in similar form and all those can be moved at once sometime later if required.
> ZCS-736 Universal UI: Calendar month view fit and finish

- WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
Issue:
- When viewing html mail content in plain text mode, script was getting executed
Resolution:
- After converting html content to plain text we need to html ecnode it so the contents will not be executed when added in dom
> ZCS-2645 Bug 108265 - Persistent XSS - message view as text [CWE-79]

- WebRoot/css/dwt.css
- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/calendar/view/ZmReminderDialog.js
- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.properties
- WebRoot/templates/calendar/Calendar.template
ZCS-2417: Universal UI: Appointment Reminder dialog
Changeset:
* ZmReminderDialog.js:
* Adding logic to show the bottom actions bar only if there are more than 1 appointments in the dialog.
* Styling changes and adding identifying CSS class names to different dialog sections.
* Calendar.template: Alignment & styling changes.
* skin.css, zm.css & dwt.css: Related styling changes to match the new UX design.
> ZCS-2417: Universal UI: Appointment Reminder dialog

- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
- WebRoot/js/zimbraMail/calendar/view/ZmFreeBusySchedulerView.js
Fixing: Free Busy calendar view breaking with latest changes.
Root cause: The same view is used in new appointment where the start date is displayed inside the scheduler. In case of Free Busy view, there won’t be any appointment associated and thus this._appt is undefined.
Changeset:
* Adding condition to check for presence of this._appt to be defined.
* Adding ZmOperation.FB_VIEW to the list of tabs to be styled as tab in Calendar App.
* Changing the delete action button to use ImgCancel.svg
> Fixing: Free Busy calendar view breaking with latest changes.

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/calendar/ZmCalendarApp.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalColView.js
- WebRoot/skins/_base/base4/skin.properties
Changes:
* `ZmCalColView.js`
* Updated and adjusted spacing between different calendar elements as per mockup
* Added logic for highlighting vertical separators for today as per mockup
* Updated logic to stretch current time indicator from end-to-end
* Updated `zm.css` and `skin.properties` as per requirement
https://jira.corp.synacor.com/browse/ZCS-749
> Updated look and feel of calendar week view and work week view as per mockup

- WebRoot/js/zimbraMail/mail/controller/ZmComposeController.js
Was removed in ZmComposeController.SETTINGS because are not used anymore.
> Cleanup of ZmComposeController.SETTINGS usage

- WebRoot/css/dwt.css
- WebRoot/css/zm.css
Fix:
* Used `transform` property to centre align container
https://jira.corp.synacor.com/browse/ZCS-2905
> ZCS-2905: Universal UI- Calendar NavToolbar filling extra space on the right, making buttons next to it unclickable.

- WebRoot/css/dwt.css
Fix:
* Increased `max-width` of `DwtConfirmDialog` to `70%`, which should be enough for all cases
* Removed unwanted margins on `DwtConfirmDialogQuestion `
https://jira.corp.synacor.com/browse/ZCS-2993
> ZCS-2993: Universal UI - Confirm Delete dialog not display properly

- WebRoot/js/zimbraMail/mail/view/ZmInviteMsgView.js
Fix:
* Setting parent of `moveSelect` container to `inviteToolbar` which was `inviteMessage` before
https://jira.corp.synacor.com/browse/ZCS-3066
> ZCS-3066: Universal UI - Closing and reopening conversation in reading pane shows empty dropdown in the reading pane.

- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.properties
Fix:
* Set `max-width` of reminder dialog and it’s subject as well
* Added custom css rule to handle very long calendar name in calendar select dropdown.
https://jira.corp.synacor.com/browse/ZCS-2997
> ZCS-2997: Universal UI - Reminder dialog should not change size for appointment with longer subjects

- WebRoot/js/zimbraMail/package/NewWindow_1.js
- WebRoot/js/zimbraMail/package/Startup1_1.js
- WebRoot/public/launchNewWindow.jsp
- WebRoot/public/launchZCS.jsp
- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.properties
- build.xml
- Use svg4everybody lib for adding support for using svg fragments in IE11
- fill: initial was not working in IE11, instead use black color
>  ZCS-904 Support SVG sprite in IE11

- WebRoot/js/zimbraMail/calendar/view/ZmCalDayView.js
- use normal for loop as forEach on NodeList is not supported in IE
> ZCS-3282 Universal UI: Exception thrown when day view is selected in calendar in internet explorer

- WebRoot/js/zimbraMail/share/view/ZmAppChooser.js
- fix issue where zooming to 200% was hanging browser
- make sure if we don't have any visible tab left then break the loop
> ZCS-2995 Universal UI : Right Navbar options got disappeared on doing zoom out and then rest to default

- WebRoot/js/zimbraMail/share/view/ZmAddressInputField.js
- remove use of textarea instead of input fields in IE, as I don't see any issues in IE11 and Edge
> ZCS-1865 Universal UI: Mail compose screen is not being rendered properly in MS Edge browser

- WebRoot/skins/_base/base4/ZmSkin.js
- WebRoot/skins/_base/base4/skin.css
- WebRoot/skins/_base/base4/skin.html
- WebRoot/skins/_base/base4/skin.properties
- add a new container which can be resized instead of resizing new button container, this way we will be having a fluid width of new button container based on it's contents
> ZCS-3228 Right-align "New" button arrow with arrows in folder tree

- WebRoot/js/zimbraMail/share/view/ZmFolderChooser.js
Changes:
* Made `ZmFolderChooser` dropdown of fixed width
https://jira.corp.synacor.com/browse/ZCS-3320
> ZCS-3320: Universal UI- Calendar list is not aligned in Move menu and incomplete calendar name is displayed if calendar name is very long

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/calendar/model/ZmAppt.js
- WebRoot/templates/calendar/Appointment.template
Changes:
* Shown max upto 3 attendees on tooltip on new line each
* Updated template to display attendee on separate row
https://jira.corp.synacor.com/browse/ZCS-3316
> ZCS-3316: Universal UI- Attendee list displayed on hover tooltip on meeting invite is broken

- build.xml
webclient is not working as it is not able to find timezones zip after changes done in https://github.com/Zimbra/zm-timezones/commit/7059681ac1fc2093ebb6ea93241a9fe6d98e7b3e, so fixing that issue
> Fix webclient build

- WebRoot/js/zimbraMail/share/view/dialog/ZmSharePropsDialog.js
- WebRoot/skins/_base/base4/skin.properties
* Positioned shared folder dialog at `center top` while opening, so that when content grows it doesn't go beyond the screen
https://jira.corp.synacor.com/browse/ZCS-2418
> ZCS-2418: Universal UI- Share folder dialog

- WebRoot/WEB-INF/tags/calendar/zoomView.tag
Fix:
* Set `zoom` param to null for close button URL
https://jira.corp.synacor.com/browse/ZCS-3570
> ZCS-3570: Unable to close time frame in Calendar with Month view

- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
When using the hotkey "/" to set focus to the search box, the current search query is added to the search box without a trailing space. This leads to the situation where anything added by the user to the search is appended to the original query, causing a malformed query string. This fix simply adds a space to the end of the query string when the search field value is set.
Manual testing has verified the fix. Additional tests will be added to the selenim test suite to future-proof the fix.
> Bug 102701: Added trailing space to search value.

- WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
ZCS-4116 8.7 patch backport for JIRA ticket ZCS-2645 - Bug 108265 - Persistent XSS - message view as text [CWE-79]
> ZCS-4116 8.7 patch backport for JIRA ticket ZCS-2645 - Bug 108265 - Persistent XSS - message view as text [CWE-79]

- WebRoot/WEB-INF/tags/mobile/moComposeCheck.tag
- WebRoot/css/ipad.css
- WebRoot/css/iphone-ext.css
- WebRoot/css/iphone-lowbw.css
- WebRoot/css/iphone.css
- WebRoot/css/xlite.css
- WebRoot/css/zmobile1.css
- WebRoot/m/mocompose
- WebRoot/messages/ZhMsg.properties
Problem : provide "add attachment" function on Mobile HTML client
Fix : 
1. Add "Attach" button on compose page
2. Add error handling code in case file size exceeds max size limit
Testing done : testing done by developer.
- Win10/Edge, IE11, Firefox, Chrome
- iPhone7/iOS11.2.5/Safari
- XperiaXZ/Android7.0/Chrome
TODO: I18N support
- Label of attach button
- New key: ZhMsg.properties -> attachLabel
Link: PR on develop branch - https://github.com/Zimbra/zm-web-client/pull/224
> snickers: NICPS-49: adding "Add Attachment" function on Mobile HTML client

- WebRoot/WEB-INF/tags/head.tag
- WebRoot/public/launchZCS.jsp
Problem: provide the ability to display banners to users on the domain or user level.
Fix : override ImgAppBanner URL with zimbraCustomAppBanner.
Testing done : testing done by developer
Related PR: https://github.com/Zimbra/zm-mailbox/pull/530
> snickers: NICPS-14: Banner Per User level and Banner Per Domain Level

- WebRoot/js/zimbraMail/mail/controller/ZmMailListController.js
- WebRoot/js/zimbraMail/share/controller/ZmBaseController.js
Problem: if email link begins with "mailto:" in message view, "mailto:" is treated as a part of an email address at actions as below.
- Find Emails -> Received From Sender: search query is "from:mailto:user@domain". The search does not work. 
- Find Emails -> Sent To Sender: search query is "tocc:mailto:user@domain". The search does not work.
- New Email: "mailto:user@domain" is added to To field in compose page
- Add To Contacts: "mailto:user@domain" is added to Email field in New Contact page
Fix: added AjxStringUtil.parseMailtoLink to remove "mailto:"
Testing done : testing done by developer. Tested the actions via the following path.
- Right-click a sender in From field of message list on message/conversation view
- Right-click a sender/recipient in message header on …
> snickers: NICPS-31: changed to remove "mailto:" from email link

- WebRoot/WEB-INF/tags/rest/restDocumentView.tag
- WebRoot/WEB-INF/tags/rest/restSlideView.tag
- WebRoot/WEB-INF/tags/rest/restSpreadsheetView.tag
- WebRoot/js/zimbraMail/package/NewWindow_1.js
- WebRoot/js/zimbraMail/package/NewWindow_2.js
- WebRoot/js/zimbraMail/package/Startup1_1.js
- WebRoot/js/zimbraMail/package/Startup2.js
- WebRoot/public/Docs.jsp
- WebRoot/public/launchNewWindow.jsp
- WebRoot/public/launchSidebar.jsp
- WebRoot/public/launchZCS.jsp
- build.xml
- Move jquery and clipboard 3rdparty libs to it's own modules
- Don't minify code of 3rdparty libraries using yuicompressor instead use already minified version that is shipped as part of 3rdparty package
- Modernizr is a special case here, it is not moved to own module as that is tightly coupled with bootstrap classes which creates issues
- Make sure JQuery is loaded before any package, as that was the case earlier also
- Load clipboard module only when it is needed, this was earlier included  as part of startup module
- Upgrade jquery version to 3.3.1-1
> ZCS-4387 Upgrade jquery in webclient

- WebRoot/WEB-INF/tags/compose/htmlCompose.tag
- WebRoot/WEB-INF/tags/options/optSignatures.tag
- WebRoot/js/zimbraMail/calendar/view/ZmCalItemEditView.js
- WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
- Add custom font size support to html client, webclient is already using this
- Remove code in ZmHtmlEditor.js which was used to solve issue related to font format selection was setting wrong value in combobox, this was happening because we were having single quotes in font_formats config of TinyMCE which is now fixed properly
- If user has default compose mode as html and when user tried to open plain text task, code was loading html mode first but before it finishes we were setting mode as plain text which was creating issues, now we are making sure that html editor is always initialized with correct compose mode
> ZCS-4023 Fix tinymce upgrade related bugs

- pkg-builder.pl
- AjxMsg.properties are already part of admin console, so no need to copy it
> ZCS-4023 try to fix build

- WebRoot/public/hostedlogin.jsp
- WebRoot/public/login.jsp
- add csrf token protection in login page, this token is non persistant
- first a unique random string is generated which is put into cookie as ZM_LOGIN_CSRF and also stored as hidden form input field as login_csrf
- when submitting login request we compare both the values if both values match then only go ahead with auth request otherwise show error to user and break login process
> ZCS-211 login CSRF protection: ZWC login form does not use a csrf token [CWE-352]

- WebRoot/js/zimbraMail/share/controller/ZmBaseController.js
Problem : "mailto:user@domain" is copied when user right-clik an email link and click "Copy"
Fix : changed to copy "user@domain" only
Testing done : testing done by developer
Checked fields:
- Email: message preview pane
- Conversation/Message view
- Text/HTML mail
- Contact: Email field
- Task: subject, location, content
Note:
Copy action on address bubble copies display name and email address.
Example: `"Last First" <user@domain>`
- from/to/cc header shown in message preview pane
- recipient in To/Cc/Bcc field in Compose page
> snickers: NICPS-138: remove "mailto:" at Copy action

- WebRoot/js/zimbraMail/abook/controller/ZmContactListController.js
Problem : "mailto:user@address" is added to To field when a contact email is "mailto:user@domain" and "New Email" is clicked
Fix : remove "mailto:" from email address
Testing done : testing done by developer
Note: The PR doesn't fix "New Email" on contact group. If an email of a contact in a contact group is "mailto:user@domain", the contact is not added to To field at "New Email" action on the contact group.
The reason not to fix it is, we need to change AjxEmailAddress.parseEmailString or AjxEmailAddress.parse, but affected area is wide. It is risky at this point.
Linked PR :
https://github.com/Zimbra/zm-web-client/pull/234
https://github.com/Zimbra/zm-web-client/pull/256
> snickers: NICPS-138: removed "mailto:" at New Email action on Contact List

- pkg-builder.pl
ZCS-4465 is really important to avoid this.
zimbra-store and zimbra-mbox-webclient-war both claiming the ownership of 
/opt/zimbra/conf 
/opt/zimbra/jetty_base/work
/opt/zimbra/jetty_base/webapps/zimbra/css 
/opt/zimbra/jetty_base/webapps/zimbra/public. 
RHEL7 packages treat this as a conflict. As per yum version on the server 2 packages can not claims same folder but two packages can add files to the same folder. 
Added 2 option 
if folder completely own by packages then use dir_list option which pass folder names --pkg-installs  
if folder owned by some other package then use file_list option which pass each file names --pkg-installs 
Need to fix ZCS-4465 to avoid this mess.
> ZCS-4758: remove conflicts when 2 packages claims same folder.

- WebRoot/messages/ZmMsg.properties
**Problem:** Errors shown on UI should be language independent
**Fix:** Create error codes and pass them instead of passing plain string message for error condition.
**Testing Done:**
1. Corrected and ran unit tests for SetRecoverAccountTest and RecoverAccountTest.
2. Manually tested responses on SOAPUI.
**Testing to be done by QA:**
1. Correct required automation.
2. Test and verify errors received in responses.
**Linked PR:**
https://github.com/Zimbra/zm-mailbox/pull/662
> ZCS-5266: Errors shown on UI should be language independent

- WebRoot/js/zimbraMail/mail/ZmMailApp.js
- WebRoot/public/login.jsp
- If zimbraFeatureConversationsEnabled is false then make sure zimbraPrefGroupMailBy is also changed to 'message' instead of 'conversation' for first load
> ZBUG-512 Webmail empty at first login

- WebRoot/public/login.jsp
Added logic in login.jsp file to show/hide "Forgot Password" link. This checks against the zimbraFeatureResetPasswordStatus which is set with the domainInfo flag.
To test use zmprov to change this attribute on the domain level and then restart mailbox.
zmprov md [DOMAIN] zimbraFeatureResetPasswordStatus disabled
zmmailboxdctl restart
Confirm link doe NOT show.
zmprov md [DOMAIN] zimbraFeatureResetPasswordStatus suspended
zmmailboxdctl restart
Confirm link doe NOT show.
zmprov md [DOMAIN] zimbraFeatureResetPasswordStatus enabled
zmmailboxdctl restart
Confirm link DOES show.
> bugfix/ZCS-5595 Add logic to show hide forgot password link

- WebRoot/m/zmain
Need to remove the copyright from the mobile view of the page.
> NICPS-416: ZWC Mobile View remove SYNACOR and Zimbra Name from Copyright

- WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
Fixes Uncaught TypeError: Cannot set property 'disabled' of null at ZmComposeView.enableInputs
> Fix TypeError

- WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
Inline pdf attachments are being converted to actual attachment as we are
considering inline-pdf as non renderable with html editor mode as well.
Fixing this by considering inline-pdf as non-renderable in case of
Text editor only.
> ZBUG-623 : Prevent attachment duplication while saving or sending email.

- WebRoot/js/zimbraMail/share/ZmUploadManager.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmUploadDialog.js
NICPS-517: Add check for file content type while uploading the file in the briefcase.
**Issue**: While uploading the files in the briefcase, the extensions were being checked against the allowed file extension. But, the actual file content was not getting checked. If a user manipulates the file extension, then security can be bypassed easily.  Refer NICPS-378 for more info on extension check.  There was a bug with existing functionality of extension checking which allows all the files to be uploaded while uploading multiple files and providing a valid file as the last file.
**Solution**: To check the file type regardless of the extension, we need to check the file signature and match it with the different file signatures of various file types. This requires the browser's FileReader API. …
> NICPS-517: Add check for file content type while uploading in the briefcase.

- WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
Removing code introduced in ZBUG-623 as this issue caused by
those changes.
Fixing ZBUG-821 and ZBUG-623 using a common fix.
We just ignore pdf attachments incase if those were added to
body part as inline attachment.
> ZBUG-821 : Fix missing pdf attachment regression.

- WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
NICPS-532: Remove text PramukhIME from typing help titles
**Issue**:  The text 'PramukhIME' was coming up at various screens where language plugin was getting used
**Resolution**:  Updated the title to 'Typing Help"
> NICPS-532: Remove text PramukhIME from typing help titles

- WebRoot/js/zimbraMail/share/ZmUploadManager.js
NICPS-537: Add check for zimbraFileTypeCheckEnabled attribute
An attribute named zimbraFileTypeCheckEnabled is added. This boolean attribute is responsible for enabling/disabling of file content type check while uploading a file in the briefcase.
> NICPS-537: Add check for zimbraFileTypeCheckEnabled attribute

- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
When selected a single calendar from the list of calendar from the list of calendar and creating a new event the add dialog selects the calendar that is selected .
If multiple calendar are selected and a new event is been created the add dialog chooses the default calendar.
If none of the calendar is been selected and a new event is been created the add dialog chooses the default calendar.
> ZCS-6680 : When a single calendar is selected new events will be created in the calendar selected instead of the default calendar

- WebRoot/js/zimbraMail/calendar/view/ZmCalColView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalDayView.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmFolderDialogTabView.js
* make sure to add elements in DOM before calling getComputedStyle, as Edge 44 become stricter and doesn't return any values from getComputedStyle when it is not part of DOM hierarchy
> ZBUG-747 cannot login to ajax client on Edge 44

- WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
Have made covert_urls to false has it was truncating the url when added in source code in html format  and even checked ZBUG-1278 is also working as expected.
> ZBUG-546 : As the urls were getting truncated have in the source code in HTML format 

- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
- WebRoot/js/zimbraMail/package/ContactsCore.js
- WebRoot/js/zimbraMail/package/Startup1_2.js
HAB was missing in detached window because the hab-controller
related code is not there in Contacts-core package for detached
window.
Moved the controller file to Contacts-core package.
Additionally, Registered HAB tree is for child-window organiser.
> ZCS-6897 : Fixing HAB in detached window.

- WebRoot/js/zimbraMail/prefs/view/ZmFilterRuleDialog.js
A little know feature in Zimbra is that one can set filters that automate email replies. But this can only be done in the CLI.
/opt/zimbra/bin/zmmailbox -z -m myaccount@example.com afrl "Filter_name" active any address "to,cc,from" all is "otheraccount@example.com" reply "Auto reply message" stop
The filter is now shown read-only to the user, however if a longer reply message is set, the filter dialog goes outside the browser window like so:
This PR patches it to be like so:
Also, without patch the UI can still be used by dragging around the filter dialog, which makes the dialog  resize correctly eventually. But most users would not expect that.
> Fixes dialog overflow outside browser window

- WebRoot/WEB-INF/tags/infra/skinAndRedirect.tag
- WebRoot/public/Docs.jsp
- WebRoot/public/Resources.jsp
- WebRoot/public/error.jsp
- WebRoot/public/proto/index.jsp
Many attempts to exploit zimbra "skin" directory traversal bug (see https://www.exploit-db.com/exploits/30085 or its rewritten version https://github.com/nulsec/zimbra-0day/blob/master/zimbra.txt) produce the tremendous amount of exceptions in zmmailboxd.out.
This commit chain closes https://bugzilla.zimbra.com/show_bug.cgi?id=109156 by enforcing functional
sanitation of "skin" parameter. As "skin" parameter is one alphanumeric word. the proposed patches revert to Zimbra's "defaultSkin" option if supplied value is not the case.
> Enforce functional sanitation of "skin" parameter

- WebRoot/WEB-INF/tags/rest/restCalendarViewBottomToolbar.tag
**Problem:**
- ics link is not shown in calendar in separate window.
- javax.el.ELException is written in mailbox.log
Nested `$` caused the exception. Then the link was not created.
`${zm:cook(${requestScope.zimbra_target_account_name})}`
**Fixed:**
Remove nested `$`.
> ZBUG-861: fixed the expression of ics link

- WebRoot/WEB-INF/tags/mobile/moContactEmail.tag
- WebRoot/WEB-INF/tags/mobile/moContactView.tag
- WebRoot/WEB-INF/tlds/mobile.tld
[Problem]
Compose page of Standard HTML client is shown when a member of a contact group is clicked on Mobile HTML client.
[Root cause]
<app:contactEmail> was set in moContactView.tag. It called /WEB-INF/tags/contact/contactEmail.tag, which was used for Standard HTML client.
[Fix]
Add moContactEmail.tag and modify moContactView.tag to call it.
> ZBUG-725: fixed to add an email address of a member of a contact group to TO field in compose

- WebRoot/css/zm.css
- WebRoot/templates/abook/Contacts.template
**Problem:**
In edit contact group page, the right part of textarea "Or enter addresses below (comma separated)" is out of the window.
**Fixed:**
Add a classname to the textarea and set the style `width:98%;` .
> ZBUG-853: fixed width of textarea in edit contact group page

- WebRoot/js/zimbraMail/abook/view/ZmContactSplitView.js
[Problem]
Script error is shown when a contact is deleted and undo is clicked in Search tab.
[Root cause]
When two or more contacts were deleted and undo was executed, ZmItemMoveAction.multipleUndo was called. In the process, ev._details.items were set in ZmItem._doNotify. Then no error occurred in ZmContactSimpleView._changeListener.
On the other hand, when a contact were deleted and undo was executed, ZmItemMoveAction.undo was called. In the process, ev._details.items were not set because ZmItem._doNotify was not called. Then ev._details didn't have items property in ZmContactSimpleView._changeListener. As a result, '0' of undefined was referred.
[Fix]
Add ev._details.items if it is undefined.
> ZBUG-727: fixed script error at undo contact deletaion in Search tab

- WebRoot/js/zimbraMail/calendar/view/ZmApptEditView.js
[Problem]
Script error is shown at Forwarding an invitation when zimbraFeatureGroupCalendarEnabled is FALSE.
[Root cause]
_forwardToField was not initialized when zimbraFeatureGroupCalendarEnabled is FALSE. Then this._forwardToField.getValue() failed at ZmApptEditView._collectForwardAddrs
[Fix]
Change to process the following steps regardless of the value of zimbraFeatureGroupCalendarEnabled
- initialize fields and autocomplete handler
- clear fields in ZmApptEditView.cleanup
> ZBUG-726: fixed script error at Forwarding an invitation

- WebRoot/js/zimbraMail/mail/controller/ZmComposeController.js
Tinymce itself replaces blob images into base64 content automatically, and
those base64 kind of inline images gets uploaded on server as normal attachments.
We just prevent such images to be uploaded on server at all as those are already
added as base64 into the content itself.
> ZBUG-1037 : Fixing inline image issue with base64 encoding.

- WebRoot/WEB-INF/tags/rest/restCalendarViewToolbar.tag
- WebRoot/WEB-INF/tags/rest/restMultiDayView.tag
Fixed wrong labels on separate window.
**Problem 1:**
End date shown at the top-right of the page is wrong in calendar WorkWeek view.
When WorkWeek view was selected, numdays was 7 (and workDays is Mon-Fri).
restCalendar.tag
<c:when test="${view eq 'workWeek'}">
<rest:multiDayView mailbox="${mailbox}" timezone="${timezone}" date="${dateContext}" view='${view}' numdays="7"/>
</c:when>
restMultiDay.tag
<c:when test="${view eq 'workWeek'}">
<c:set var="wdays" value="1,2,3,4,5"/>
</c:when>
...
<c:set var="workDays" value="${zm:getWorkDays(wdays)}"/>
However, date range was calculated with numdays(=7).
restMultiDayView.tag
<fmt:message var="pageTitle" key="CAL_MDAY_TITLE_FORMAT">
...
<fmt:param><fmt:formatDate value="${zm:addDay(currentDay, numdays-1).time}" …
> ZBUG-860: fixed date range and altkey of Right arrow button in calendar in separate window

- WebRoot/WEB-INF/tags/mobile/moJS-iPad.tag
- WebRoot/WEB-INF/tags/mobile/moJS.tag
**Problem:**
When All in Actions is clicked, any action doesn't work on Mobile HTML client.
"anAction" parameter was passed two times in a request.
e.g.
anAction: selectAll
anAction: actionFlag
**Fix:**
Send one "anAction" in a request.
> ZBUG-856: fixed to address All and None in Actions on Mobile HTML client

- WebRoot/js/zimbraMail/mail/controller/ZmMailListController.js
**Problem:**
Unnecessary sashes are shown in context menu on a draft in Trash in conversation view mode.
**Root Cause**
Action menu buttons for draft was set when the current folder was Drafts or the type of a selected item is conversation. It didn't concider a conversation which had only a draft. Then Action menu buttons for a conversation was set on a draft, but some menu buttons were removed when the item was a draft. As a result, unnecessary sashes remained.
**Fix:**
Add a condition to check if a selected conversation consists of a draft.
> ZBUG-852: changed to set context menu for draft if a conversation has only a draft

- WebRoot/WEB-INF/tags/rest/restApptView.tag
- WebRoot/h/rest
**Problem 1:**
Language setting is ignored in calendar in separate window on web-split environment.
In WebRoot/h/rest, pageContext.request.locale was not sent from mailstore. Then English was always used.
**Fix:**
Use requestScope.zimbra_target_account_prefLocale if it exists.
---
**Problem 2:**
Button/Text links don't work on web-split environment. Most of the links are fixed on https://github.com/Zimbra/zm-mailbox/pull/847, but Close button in appointment view page still doesn't work.
action param didn't exist on `rest:calendarUrl` in restApptView.tag. Then incorrect action was added by restCalendarUrl.tag.
`https://websplit.dev.zimbra.com/home/test1@dev.zimbra.com/Calendar.html?view=month&tz=Asia%2FTokyo&date=20190207&action=view`
**Fix:**
Add an empty …
> ZBUG-859: fixed params for calendar in separate window

- WebRoot/js/zimbraMail/prefs/view/ZmFilterRuleDialog.js
**Problem:**
Focus doesn't move to next field in Create/Edit Filter dialog by pressing Tab key.
`el.getAttribute("tabindex")` always returned "0". Then tabIndexes array was not set as expected.
**Fix:**
Remove `el.getAttribute("tabindex")` and set tabIndex incrementally.
Change the tabIndex order of Name field, Active checkbox and Stop checkbox.
> ZBUG-851: fixed tabIndex in Add/Edit Filter dialog

- WebRoot/js/zimbraMail/mail/ZmMailApp.js
[Problem]
Show Conversation menu item is shown even when zimbraFeatureConversationsEnabled is FALSE.
[Root cause]
SHOW_CONV operation was always enabled in ZmMailApp.js.
[Fix]
Add ZmSetting.CONVERSATIONS_ENABLED as a condition to enable/disable the operation.
> ZBUG-669: changed to hide Show Conversation when zimbraFeatureConversationsEnabled is FALSE

- WebRoot/WEB-INF/tags/mobile/moJS.tag
**Problem:**
Toolbar appears in a wrong place after an action is executed and another message is selected on Mobile HTML client.
When an item is checked, style "display: table" is added to the following div and then the toolbar (id='fbbar') appears
`<div id="fbbar" class="tb tbl" style="display: table; transform: translateY(0px);">`
The position of fbbar is "absolute".
#fbbar {
position: absolute!important;
top: 40px!important;
-webkit-transition: -webkit-transform .2s ease-out;
z-index: 100!important;
border-bottom: 2px solid silver;
}
When an action is executed, the following msgDiv is added and then a result message (like "1 message has been marked read") is shown.
`<div class="container tbl" id="msgDiv" onclick="return toggleElem(this);">`
At this point, the position …
> ZBUG-850: fixed to remote msgDiv when item is checked/unchecked

- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
ZBUG-724 : Fix spacing issue for search bar text.
Earlier, "undefined" was shown in the search field when Calendar or Preferences tab is clicked.
It was due to the concatenation of undefined variable and a space character.
> ZBUG-724 : Fix spacing issue for search bar text

- WebRoot/WEB-INF/tags/mobile/moContactAction.tag
Problem: Only one of selected contacts is added to To/Cc/Bcc field even when two or more contacts are selected and To/Cc/Bcc action is executed on Mobile HTML client.
Root cause:
Selected contacts were not listed but only one of selected contacts was specified as a parameter in redirect url.
Fix:
Join selected contacts' email addresses with "comma+whitespace" and set it to redirect url.
> ZBUG-848: fixed to add all selected contacts to To/Cc/Bcc field

- WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
Using typeof does not avoid the error. @silentsakky perhaps you can merge it.
> Avoid TypeError in ZmComposeView.prototype.enableInputs

- WebRoot/css/iphone.css
[Problem]
Blank button appears when a checkbox of a message/conversation/contact is checked on Mobile HTML client.
[Root cause]
ImgCancel class was set in HTML code but style was not set.
[Fix]
Add styles to the button and the class.
> ZBUG-723: added styles to show cancel button on toolbar

- WebRoot/js/zimbraMail/share/model/ZmOrganizer.js
**Problem:**
When user tries to download files in a sub folder of shared folder at a time, the page is reloaded unexpectedly. User needs to download files one by one.
Rest URL was set in a root folder of a shared folder, but it was not set in a sub folder. Then Ajax client accessed a wrong URL.
Request URL on a root folder: `https://SERVER/home/EMAIL/parent/parent?fmt=zip&list=ITEM_ID`
Request URL on a sub folder: `https://SERVER/?fmt=zip&list=ITEM_ID`
**Fix:**
Fixed `ZmOrganizer#getOwnerRestUrl` to find parent's `restURL` recursively and set a correct `path`.
**Affected area:**
`ZmOrganizer#getOwnerRestUrl` is called only when downloading files in a shared folder on Briefcase.
> ZCS-7729: fixed rest url of shared folder in briefcase

- WebRoot/js/zimbraMail/abook/controller/ZmContactController.js
- WebRoot/js/zimbraMail/abook/model/ZmContact.js
Fixed issue i.e Contact Group name is not updated in the contact list after renamed or deleted.
> ZBUG-1100: Contact Group name is not updated in the contact list after renamed or deleted

- WebRoot/public/login.jsp
Mobile users will be moved to zimbrax if they don't select any option from dropDown(if zimbrax is present) and if zimbrax is supported they will be moved to default login page instead of touch-client in mobile.
> PREAPPS-3911 : Mobile users taken to deprecated mobile login on Z8 back end when default set to "Zimbra X"

- WebRoot/js/zimbraMail/prefs/view/ZmZimletsPage.js
Implemented functionality to hide modern zimlets in classic UI.
> PREAPPs-4652: Rename Modern zimlets to have user friendly names

- WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
Added style properties to iframe doc to fix scrollbar height issue.
> ZBUG-1656:- Email content for webex invite is shown with unexpected blank zones.

- WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
Updated check to skip adding inline attachments as attachment whose content type is text/html.
> ZBUG-1813:- "unknown text/html" attachments being included when replying/forwarding some emails

- WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
**Before**:- while replying we were adding the incoming css styles to the first element present 
in the body which was <br/> tag which causes issue after performing multiple backspace
**Now**:-  we are searching for the data-marker of replying message i.e  '__QUOTED_TEXT__'
and inserting css div style before the '__QUOTED_TEXT__' data marker.
> ZBUG-1551:- Web client allow editing raw HTML in email causing blank emails in Outlook

- WebRoot/js/zimbraMail/share/model/ZmMetaData.js
- WebRoot/js/zimbraMail/share/model/ZmSettings.js
Removed OPTIONS_ENABLED check when use is doing implicit settings.
> ZCS-9595:- Status of expanded/collapsed of a folder is not saved when zimbraFeatureOptionsEnabled is FALSE

- WebRoot/js/zimbraMail/calendar/ZmCalendarApp.js
**Issue:** Error while setting a shared calendar as a default calendar
**Reason:** Shared id was being sent, whereas the API expected the default id (integer value).
**Fix:** Default id is now sent for all calendars.
> ZCS-10004: Ability to set shared (write-able) calendar as a default calendar

- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
Fixing wrong appointment name in delete-confirmation dialog.
Remove unnecessary condition to check operation mode.
Mode were remains same while deleting instance of another appointment.
> ZBUG-1875 : Fixing wrong appointment name.

- WebRoot/messages/ZmMsg_en_US.properties
**Problem:**
Zimbra Skin Broken.
**Workaround:**
Created an empty `ZmMsg_en_US.properties` file which will be used for overriding the keys from `ZmMsg.properties` file.
`ZmMsg.properties` is getting overriden with the use of this method when we place this file in the message directory of the skin. So, the workaround as of now is that it is expecting a ZmMsg_en_US.properties file in the message directory of the skin from where it reads the overriden keys and the default value is read from the original `ZmMsg.properties` file.
> ZBUG-1220: Workaround for Zimbra Skin Broken

- WebRoot/public/login.jsp
When IE-11 browser is detected, user should be logged into Classic UI.
On login page, do not show Modern UI in dropdown. It will be Classic and Default.
> PREAPPS-5930 : Log into Classic UI in case of IE11.

- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
We prompt user to remove deleted shared account from folder tree for
each data source. But only the last reponsed folder were getting moved to trash.
The reason was overlappint prompt dialog.
Fix this by handle all of the deleted data sources in one prompt dialog.
Now all the deleted datasources included in one prompt dialog and getting moved to trash.
> ZBUG-2015 : Fix issue while delete multiple shared account from settings.

- WebRoot/js/zimbraMail/mail/view/ZmMailMsgView.js
Problem:- Classic Web Client: Stored XSS Vulnerability in ZmMailMsgView.js
Cause:- This issue is caused by ZCS-7512. https://github.com/Zimbra/zm-web-client/pull/508/files
When we remove ZCS-7512 code the above issue gets automatically fixed.
The root cause of ZCS-7512 is backend is sending wrong `<form />` tag html when OWASP enabled
> ZBUG-2282: Reverting ZCS-7512 changes to fix.

- WebRoot/messages/ZtMsg_de.properties
The old "bis" means until as in "nine to five". The new "an" implies a recipient as in "message to somebody".
> Fix German "to" field

- WebRoot/js/zimbraMail/calendar/ZmCalendarApp.js
- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalColView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalDayView.js
We are currently facing usability issues while accessing overlapping less then 30 minutes appointments.
Trying to increase calendar time slots height.
We now can have 15 mins slots instead of 30 mins.
Which will help to increase the usability with small time duration meetings/appointments.
> ZCS-10874 : Increase HOUR_HEIGHT to have 15 minutes slot.

- WebRoot/js/zimbraMail/calendar/view/ZmApptEditView.js
- WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
- WebRoot/js/zimbraMail/share/controller/ZmBaseController.js
- WebRoot/js/zimbraMail/share/view/ZmAddressInputField.js
**Problem:**
When Contacts feature is disabled (i.e. zimbraFeatureContactsEnabled FALSE), a script error dialog is shown in the following cases:
(A) go to New/Edit Appointment page, add a location and right-click the address bubble of the location
(B) show a message and right-click an address bubble of a sender or a recipient
(C) go to New Appointment page and click Attendees or Optional button. (Note: no error is thrown when you go to Compose page and then go to New Appointment page.)
(D) right-click an appointment, click Forward and click To button
(E) disable GAL feature (i.e. zimbraFeatureGalEnabled FALSE) and go to New Appointment page
(F) right-click a message and click Create Appointment. See also https://github.com/Zimbra/zm-zimlets/pull/50
**Changes:**
(A) fixed …
> ZCS-10908: fixed script errors raised when Contacts is disabled

- WebRoot/js/zimbraMail/calendar/view/ZmApptEditView.js
**Problem:**
"Show Equipment" does not work in the following case:
1. open New Appointment tag, click "Show Equipment" and close the tab
2. open another New Appointment and click "Show Equipment". Equipment field does not appear.
3. click "Show Equipment" again. Equipment field appears.
*Change:*
* reset the status of Show/Hide Equipment when a new/edit appointment tab is closed.
> ZCS-10909: reset the status of Show Equipment

- WebRoot/js/zimbraMail/calendar/controller/ZmApptComposeController.js
- WebRoot/js/zimbraMail/calendar/model/ZmCalItem.js
**Problem:**
Conflicting Resources dialog is not shown on all day appointment even when GetFreeBusyRequest/Response detects a conflict.
End date time is calculated as 00:00:00 of the day in conflict check process at send/save action.
For example, start date and end date of all day appointment is set to 24/Sep/2021, both start and end time is set to "24/Sep 2021 00:00:00" in CheckRecurConflictsRequest.  End date time needs to be "25/Sep/2021 00:00:00" to detect a conflict on 24/Sep.
**Change:**
* Add one day (24 hours) to end time for conflict check (CheckRecurConflictsRequest) when all day checkbox is checked.
* Add timezone of start and end time to CheckRecurConflictsRequest.
> ZCS-10910: fixed end date time of all day appointment in conflict check

- WebRoot/js/zimbraMail/calendar/view/ZmApptRecurDialog.js
**Problem:**
Invalid date is set in the following case:
1. New Appointment -> Custom in repeat setting
2. select a day of week in Monthly repeat
3. change to Weekly repeat and click OK
4. NaN/NaN/0NaN is set in Start and End date
In `ZmApptRecurDialog.prototype._selectChangeListener`, a clicked item is checked if it is DwtMenuItem. The processes in the `if` statement is for weekly repeat setting. However, other drop down menu options in Monthly or Yearly repeat are also instances of DwtMenuItem.
**Change:**
Adding a condition to check if the current setting is for weekly repeat.
> ZCS-10916: added condition to check weekly repeat

- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
**Problem:**
* Appointments disappear when the appointments are not cached and view is refreshed.
(example of the trigger of refresh)
* change folder color
(cases that the issue happens)
(A) login, go to Calendar immediately and change folder color immediately (before SearchRequest/BatchRequest is called)
(B) enable Calendar app only, login and change folder color immediately 
When `ZmCalViewController.prototype._refreshAction` is called with `dontClearCache true`, `this.apptCache.clearCache();` is not called. In this case, appointments are removed from the view and (re)loaded from cache. However, there is a case that appointments shown in the view are not stored in cache. As a result, no item is shown in the view at refresh.
**Fix:**
Add a logic to check if there is a …
> ZCS-11065: changed to fetch appointments if they have not been cached

- WebRoot/js/zimbraMail/core/ZmAppCtxt.js
- WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
- WebRoot/js/zimbraMail/share/model/ZmSettings.js
Backend PR: https://github.com/Zimbra/zm-mailbox/pull/1213
Jira ticket: https://jira.corp.synacor.com/browse/ZBUG-1280
Displaying the spell button on compose view only when zimbraSpellCheckURL returns atleast one url on the primary server. This also disables the mandatory spell check button since there is no active service to check the spelling.
> Zbug-1280 showing spellcheck button only when spellcheck service is enabled

- WebRoot/js/zimbraMail/share/view/htmlEditor/ZmHtmlEditor.js
**Problem:**
When a file is attached (= pasted) from clipboard in Compose page, the file name of the attachment is changed to some numeric string.
`ZmHtmlEditor.prototype.onPaste` is called when a file is pasted from clipboard. File data is gotten in the following code:
```
var items = ((ev.clipboardData &&
(ev.clipboardData.items || ev.clipboardData.files)) ||
(window.clipboardData && clipboardData.files)),
item = items && items[0],
file, name, type,
view;
if (item && item.getAsFile) {
file = item.getAsFile();
name = file && file.fileName;
type = file && file.type;
} else if (item && item.type) {
file = item;
name = file.name;
type = file.type;
}
```
Object:
```
ev.clipboardData is DataTransfer
ev.clipboardData.items is DataTransferItemList
ev.clipboardData.items[0] is …
```
> ZBUG-2423: set correct file name when a file is pasted from clipboard to draft

- WebRoot/js/zimbraMail/mail/model/ZmMailItem.js
**Problem:** If a contact exists, its display name is always used for an address, even if the delivered name is more descriptive, e.g. contact says "user1" and the original message had "User One <user1@example.com>".
**Solution:** Use the more descriptive name for To/From displays.
**Fix:** Fixed ZmMailItem.prototype._parseParticipantNode to use the passed From if the contact is only the user part of the email address.
**Testing:** Deploy zm-web-client branch, follow instructions in [ZBUG-2236](https://jira.corp.synacor.com/browse/ZBUG-2236), verify that delivered fullname is used in final step for viewing and replying.
> ZBUG-2236: Show delivered From if no good contact fullname

- WebRoot/js/zimbraMail/abook/model/ZmContactList.js
- WebRoot/js/zimbraMail/core/ZmAppCtxt.js
**Problem:**
Display Name or Image of a contact in a sharing contact folder is not used in Mail app until the folder is clicked.
Steps to reproduce:
1. on user A,
* create a contact which has an email (e.g. userC@dev.zimbra.com), display name and an image file.
* share a contact folder which contains the contact with user B.
2. on user B,
* accept the share. The contact can be read.
* receive an email from userC@dev.zimbra.com
3. on user B,
* relogin and click the message
* the display name or the image of the contact in the sharing folder is not shown in message preview.
4. on user B,
* relogin, go to Contacts and click the sharing folder
* go to Mail and click the message
* the display name and the image of the contact in the sharing folder are shown in message preview.
Expected …
> ZBUG-1945: load sharing folders in Contacts

- WebRoot/js/zimbraMail/share/zimlet/handler/ZmEmailObjectHandler.js
**Problems:**
1. When a message body contains mailto string which has angle brackets `<>` like `<mailto:account1@dev.zimbra.com?subject=sample%20message>`, the link includes the last `>`.
(i.e. `mailto:account1@dev.zimbra.com?subject=sample%20message>`)
Then by clicking the link, "sample message>" is set in subject field of new compose page.
2. When the link is clicked, the values of subject and body need to be sanitized before they are added to the fields in new compose page.
**Definition of the format of mailto link:**
It is defined in RFC 6068, 3986 and 2234.
```
(RFC 6068)
mailtoURI    = "mailto:" [ to ] [ hfields ]
to           = addr-spec *("," addr-spec )
hfields      = "?" hfield *( "&" hfield )
hfield       = hfname "=" hfvalue
hfname       = *qchar
hfvalue      = *qchar …
```
> ZBUG-2164, ZCS-11153: fixed parameter handling on mailto link

- WebRoot/js/zimbraMail/core/ZmAppCtxt.js
**Problem:**
Spell check button does not appear in compose page when language setting is Catalan. (zimbraPrefLocale ca)
Aspell Catalan dictionary was not included in Zimbra.
**Changes:**
* Add Catalan dictionary on https://github.com/Zimbra/packages/pull/149
* Add `ca` to `ZmAppCtxt.AVAILABLE_DICTIONARY_LOCALES`
> ZBUG-2145: added Catalan to aspell support locale

- WebRoot/WEB-INF/tags/calendar/monthView.tag
- WebRoot/WEB-INF/tags/calendar/multiDay.tag
When rendering the basic html client calendar view, protect against XSS using the fn:escapeXML function to render newAppt
> ZCS-11122: Protect against XSS while rendering list view in /h/calendar

- WebRoot/css/common.css
**Problem:**
On Linux, when a dialog like Move Message is shown, the background does not become transparent but blue background appears. The background should become transparent in the same way as on Windows and Mac.
Styles of BusyOverlay and VeilOverlay were different between Linux and others. According to the comment in `common.css`, it was due to performance problem with opacity style.
No performance issue was observed with opacity style. Linux-specific style is no longer necessary.
**Changes:**
Change to use `BusyOverlay` and `VeilOverlay` classes regardless of client OS.
* Remove `BusyOverlay-linux` and `VeilOverlay-linux` classes on https://github.com/Zimbra/zm-ajax/pull/95
* Remove the style for the classes.
> ZBUG-1853: removed Linux-specific BusyOverlay and VeilOverlay

- WebRoot/js/zimbraMail/abook/model/ZmContact.js
**Problem:**
When a photo of an account is set, the photo is not shown in a contact in Global Address List.
**Steps to reproduce:**
1. log in to an account on Modern UI
2. click "Change Profile Image" and add a photo. It is saved in the account's `thumbnailPhoto` attribute.
3. force GalSync. `$ zmgsautil forceSync -a GALSYNC_ACCOUNT -n InternalGAL`
4. relogin on Modern UI, go to Contacts and click Global Address List in folder tree
5. relogin on Classic UI, go to Contacts and click the contact of the account in `galsync.xxxx_InternalGAL` folder
6. a photo is not shown as an image of the contact. Instead, base64 encoded string of the photo is shown in Other (thumbnail Photo) field.
**Change:**
* Address thumbnailPhoto in `ZmContact.prototype.getImageUrl` if it exists
* Add thumbnailPhoto …
> ZBUG-2621: show thumbnail photo in GAL

- WebRoot/js/zimbraMail/share/zimlet/handler/ZmEmailObjectHandler.js
**Problem:**
When an action in right-click menu is executed on an email link which has "mailto:", the string "mailto:" is included as follows:
Example of a mailto link:
`<a href="mailto:user1@domain1.zimbra.com">user1@domain1.zimbra.com</a>`
Bahavior before the fix:
On message/conversation/contact/appointment/task view,
* Copy: `mailto:user1@domain1.zimbra.com;` is copied to clipboard
* Find Emails: Search is not executed due to an error. "Unable to parse the search query" is shown in a toaster.
* Received From Sender -> search query is `from:mailto:dummy@domain1.zimbra.com`
* Sent To Sender -> search query is `tocc:mailto:user1@domain1.zimbra.com`
* New Email: `mailto:user1@domain1.zimbra.com` is set in To field
* Add To Contacts: `mailto:user1@domain1.zimbra.com` is set in Email field
* …
> ZBUG-2649: removed "mailto:" from actions on email object

- WebRoot/public/error.jsp
On ZCS9, the errorcode field is not properly escaped. This fixes that.
> ZBUG-2084: Prevent Javascript insertion into the error.jsp page on Zimbra9

- WebRoot/public/modern.jsp
Deep linking modern ui resource (i.e. /modern/calendar) doesn't get redirect automatically after login
Get deep linking resource from RelayState param and redirect it if it's value start with `/modern/`
> PREAPPS-6566: Direct access to calendar URL

- WebRoot/WEB-INF/tags/searchPageOffset.tag
Problem: "max" parameter was not sanitized in the classic version.
Solution: Applied sanitization on "max" parameter in classic version and fix the problem.
> ZBUG-11203 Fix max parameter sanitization issue

- WebRoot/WEB-INF/tags/ads.tag
Problem: This is a sanity issue and users can post HTML/Script content with URL parameters.
Solution: Added escape-XML method in URL params and sanitized them.
Impact: If the user will pass the HTML/script tag in the URL ads parameter, it will be sanitized, and no alert dialog will appear.
> ZBUG-2659 Fix XSS security issue on html client

- WebRoot/js/zimbraMail/tasks/ZmTasksApp.js
- WebRoot/js/zimbraMail/tasks/view/ZmTaskListView.js
Problem:
- Sort order selected by user for Task folders is not getting saved/remembered.
- Whatever sort order used by user gets overwritten with default sort order.
- Sort order is being saved in zimbraPrefSortOrder for Task view only.
- Sort order should be saved in zimbraPrefSortOrder for every Task folder.
Solution:
- Sort order is now saved in zimbraPrefSortOrder for every Task folder.
- Different sort order can be saved for different Task folders.
> ZBUG-2322 : Fix sorting in Tasks.

- WebRoot/public/login.jsp
- Redirecting to zimbraWebClientLogoutURL on SSO environment without terminating authentication on Logout event. SAML is responsible to deregister auth Token (See https://github.com/Zimbra/zm-saml-consumer-store/pull/11)
> ZBUG-2426: SAML SP-initiated logout does not work - zimbraWebClientLogout

- WebRoot/WEB-INF/tags/message/body.tag
- WebRoot/WEB-INF/tags/message/displayMessage.tag
- WebRoot/WEB-INF/tags/message/messagePrintView.tag
Problem: "counter" parameter can accept HTML entity from URL and it needs to be sanitized. 
Solution: "counter" parameter sanitized with the method and after sanitization, it is working fine.
> ZCS-11201 Fix counter parameter sanitized issue

- WebRoot/js/zimbraMail/share/model/ZmFolderTree.js
This proposed solution prevents the folder from being created in the model if sharing is disabled.
> ZBUG-1921: Attribute zimbraFeatureSharingEnabled does not work with classic UI

- WebRoot/js/zimbraMail/calendar/view/ZmCalColView.js
Made changes in calendar/view/ZmCalColView.js file to _gridMouseUpHdlr method to pass calendar id to newAppointmentHelper and newAllDayAppointmentHelper methods for creating new appointments and new all day appointments respectively on clicking column in calendar day view.
> ZBUG-2611: Wrong default calendar when creating appointment via double click.

- WebRoot/js/zimbraMail/share/view/ZmSearchResultsToolBar.js
On performing a blank search using the topmost search bar with 'Include shared items' checked, search results toolbar was being populated with a query of shared items' ids. Changes have been made in share/view/ZmSearchResultsToolbar.js file to setSearch method to perform a check for the user entered search query. The search results toolbar will be populated with the user entered search query only if it exists.
> ZBUG-1539: blank search : 'include shared items' shows inid:<number> in search query

- WebRoot/js/zimbraMail/abook/controller/ZmAddrBookTreeController.js
- WebRoot/js/zimbraMail/briefcase/controller/ZmBriefcaseTreeController.js
- WebRoot/js/zimbraMail/calendar/controller/ZmCalendarTreeController.js
- WebRoot/js/zimbraMail/prefs/view/ZmSharingPage.js
- WebRoot/js/zimbraMail/share/controller/ZmFolderTreeController.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmFolderNotifyDialog.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmFolderPropsDialog.js
- WebRoot/js/zimbraMail/tasks/controller/ZmTaskTreeController.js
- There is certain possibility that user wants to share calendar folder but somehow selection changes and share folder dialog takes root folder for sharing
- User is not aware about this and unintentionally share the root folder which is problematic
- So have added a check to ignore action and show error message when user encounters this situation
- We still need to find exact steps to reproduce this problem to reliably investigate it
> ZBUG-2821 Prevent root folder sharing from webclient

- WebRoot/WEB-INF/tags/img.tag
Problem: "title" was not properly sanitized.
Solution: Sanitized "title" properly for HTML mode.
> ZCS-11202: Fix title sanitization in html

- WebRoot/js/zimbraMail/tasks/view/ZmTaskListView.js
- This issue is occuring due to zimbraPrefSortOrder having 'TKL-main:dateDesc' value which is not supported by Task
> ZBUG-2958 Tasks section/tab doesn't work after latest patch.

- WebRoot/js/zimbraMail/briefcase/view/ZmPreviewPaneView.js
- Removed `fmt=native` query param from file preview request to show preview using onlyoffice formatter.
> ZCS-12131 Classic UI shows briefcase file preview using native formatter instead of onlyoffice

- WebRoot/js/zimbraMail/briefcase/model/ZmBriefcaseItem.js
- Evaluating briefcaseItem permission to shows txt to doc converting dialog on Files shared with me folder's item.
See this pull request: https://github.com/ZimbraOS/zm-modern-zimlets/pull/198
> ZCS-11881: Opening txt file (who has edit access) from files shared with me folder doesn't warn for converting into docx format

- WebRoot/js/zimbraMail/calendar/ZmCalendarApp.js
- WebRoot/js/zimbraMail/share/view/ZmAppChooser.js
- WebRoot/skins/_base/base3/skin.html
- WebRoot/templates/share/Widgets.template
Resolved following issues.
**1.3.1_aria-selectedAttributeMissingForHeaderTABs_Global.docx**
> - Fixed existing code for adding/removing aria-selected='true'.
> - Set role='tabpanel' attribute on app details area.
> - Assigned aria-controls attribute to each app buttons.
**1.3.1_SR is reading the background content even the popup is active.docx**
> - Preventing access of background element by keyboard by focusing on current focused element on dialog if dialog having one element.
> - Set aria-modal='true' to the dialog.
**4.1.2_aria-level wont support for div.docx**
> - Set missing role='heading' attribute to correct element.
> - Updated existing code to set aria-level and aria-labelledby attribute to correct element.
> - Set missing role='heading' attribute to correct element.
> - Updated …
> ZCS-12397: WCAG | Fixed medium complexity Aria issues part-1

- WebRoot/public/login.jsp
Issue: The login page in classic UI supports arbitrary data in the username field so that any attacker can pass special characters in the username and try to execute JavaScript.
This implementation makes use of `fn:escapeXml` to escape the value assigned to **_trimmedUserName_** which is later used for validating the zimbraPasswordAllowUsername rule.
> ZCS-12376: Cross Site Scripting in Login Page

- WebRoot/css/dwt.css
- WebRoot/js/zimbraMail/abook/view/ZmGroupView.js
- WebRoot/js/zimbraMail/calendar/view/ZmApptAssistantView.js
- WebRoot/js/zimbraMail/calendar/view/ZmApptEditView.js
- WebRoot/js/zimbraMail/calendar/view/ZmAttendeePicker.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalItemEditView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalendarPrefsPage.js
- WebRoot/js/zimbraMail/calendar/view/ZmFreeBusySchedulerView.js
- WebRoot/js/zimbraMail/calendar/view/ZmLocationSuggestionView.js
- WebRoot/js/zimbraMail/calendar/view/ZmScheduleAssistantView.js
- WebRoot/js/zimbraMail/calendar/view/ZmSuggestionsView.js
- WebRoot/js/zimbraMail/calendar/view/ZmTimeSuggestionPrefDialog.js
- WebRoot/js/zimbraMail/calendar/view/ZmTimeSuggestionView.js
- WebRoot/js/zimbraMail/mail/view/prefs/ZmMailPrefsPage.js
- WebRoot/js/zimbraMail/prefs/view/ZmFilterRulesView.js
- WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js
- WebRoot/js/zimbraMail/prefs/view/ZmPriorityMessageFilterDialog.js
- WebRoot/js/zimbraMail/prefs/view/ZmSharingPage.js
- WebRoot/js/zimbraMail/prefs/view/ZmZimletsPage.js
- WebRoot/templates/calendar/Appointment.template
**2.1.1_Checkboxes are not accessible with keyboard.docx**
> Fixed. Now user can interact with Calendar folder's checkbox using keyboard spacebar. 
**2.1.1_UnabletoAccessInteractiveElementswithKeyboard.docx**
> Fixed. All interactive elements of appointment dialog are accessible using Tab and Arrow keys. User can access toolbar option with keyboard Left & Right arrow key once focus comes to `Save & Close` button.
> Also, Added keyboard accessibility support on `Find Locations`, `Find Equipments`, `Suggest Time` (except mini calendar component which will be handled in ZCS-12553) and `Suggest location` panel. 
**2.1.1_access issue-Contacts Group.docx**
> Fixed. Now user can access all the interactive elements using keyboard Tab key.
**2.1.1_access issue-Preferences.docx** 
> 1. `Preferences …
> ZCS-12531: WCAG | Classic UI | Medium Complexity | Keyboard issues Part - 1

- WebRoot/js/zimbraMail/share/model/ZmSettings.js
**Problem:**
When Preferences page is accessed directly by adding `app=options` param in the URL, Zimlets tree is show in the left pane of Preferences.
**Change:**
Add condition check to ZmSettings.js
> ZCS-12586: fixed not to show Zimlets tree in the left pane of Preferences

- WebRoot/js/zimbraMail/abook/view/ZmEditContactView.js
- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
- WebRoot/js/zimbraMail/calendar/view/ZmApptAssistantView.js
- WebRoot/js/zimbraMail/calendar/view/ZmLocationSuggestionView.js
- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
- WebRoot/js/zimbraMail/mail/view/ZmMailListView.js
- WebRoot/js/zimbraMail/mail/view/prefs/ZmMailPrefsPage.js
- WebRoot/js/zimbraMail/share/controller/ZmListController.js
- WebRoot/js/zimbraMail/share/controller/ZmSearchResultsController.js
- WebRoot/js/zimbraMail/share/view/ZmNavToolBar.js
- WebRoot/templates/share/App.template
**2.1.1_Not able to access interactive elements with keyboard.docx**
> Fixed the issue of accessing Day, Week, Work week toolbar elements using keyboard left/right arrow keys. 
> The changes of this fixes are also applicable on Task toolbar. Previously, user stuck between Left/Right navigation arrow icons on task toolbar.
**2.1.1_Unable to access the calendar Popup with keyboard.docx**
> Added support to access calendar popup element using keyboard Tab and Arrow keys. 
> The changes are applicable to every calendar popup + mini calendar. 
**2.1.1_access issue-Mail.docx**
> Added support to access Mail list header items using keyboard Tab and left, right arrow keys.
> Added support to access Logo icon + MTS theme's customise search panel.
See the changes of zm-ajax …
> ZCS-12553: WCAG | Classic UI | Medium Complexity | Keyboard issues Part - 2

- WebRoot/js/zimbraMail/core/ZmAppViewMgr.js
**Problem:**
* When a user log in on Classic UI with `app=options` parameter in the URL, Preferences page is shown as the initial app. Then if any setting is modified and saved, Mail app is shown even when zimbraFeatureMailEnabled is FALSE.
* When an administrator clicks View Mail to on Admin Console, login on Classic UI, and add `app=options` param to the URL, Preferences page is shown. Then if any setting is modified and saved, Mail app is shown even when zimbraFeatureAdminMailEnabled is FALSE.
**Change:**
Use default start app as a target of page transition after the save, rather than Mail app.
> ZBUG-3142: changed to use default start app in case Mail feature is disabled

- WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js
- WebRoot/js/zimbraMail/abook/view/ZmEditContactView.js
- WebRoot/js/zimbraMail/mail/view/ZmMailConfirmView.js
- WebRoot/js/zimbraMail/share/view/ZmExportView.js
- WebRoot/js/zimbraMail/share/view/ZmImportView.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmUploadDialog.js
**2.1.1_access issue graphic-New Contacts.docx**
- Fixed it by adding `Enter` key support, When focus is on user graphic icon then user need to press Enter key to open `upload image` dialog.
**2.1.1_access issue dialog-Mail.docx**
This issues are happening on client installed zimlets which are available under https://stash.corp.synacor.com/projects/ZIMBRA/repos/mail-client/browse/zimbra/zimlets
- Fixed all this issues. Changes are present at https://stash.corp.synacor.com/projects/ZIMBRA/repos/mail-client/pull-requests/336/overview
**1.4.3_contrast issue text dialog-Mail.docx**
- Fixes present at https://stash.corp.synacor.com/projects/ZIMBRA/repos/mail-client/pull-requests/336/overview
**2.1.1_access issue-Preferences.docx (Fix issue-1 mentioned in the doc file)**
- Added support to …
> ZCS-12614: WCAG | Classic UI | Medium Complexity | Keyboard issues Part - 3

- WebRoot/js/zimbraMail/mail/ZmMailApp.js
- WebRoot/skins/_base/base3/ZmSkin.js
- WebRoot/skins/_base/base3/skin.properties
- WebRoot/skins/bare/skin.properties
- WebRoot/skins/beach/skin.properties
- WebRoot/skins/bones/skin.properties
- WebRoot/skins/carbon/skin.properties
- WebRoot/skins/harmony/skin.properties
- WebRoot/skins/hotrod/skin.properties
- WebRoot/skins/lake/skin.properties
- WebRoot/skins/lavender/skin.properties
- WebRoot/skins/lemongrass/skin.properties
- WebRoot/skins/oasis/skin.properties
- WebRoot/skins/pebble/skin.properties
- WebRoot/skins/sand/skin.properties
- WebRoot/skins/serenity/skin.properties
- WebRoot/skins/sky/skin.properties
- WebRoot/skins/smoke/skin.properties
- WebRoot/skins/steel/skin.properties
- WebRoot/skins/tree/skin.properties
- WebRoot/skins/twilight/skin.properties
- WebRoot/skins/waves/skin.properties
**Enhancement:**
Currently favicon path is hard coded in ZmMailApp.js. Some zimbra users want to change favicon per skin.
**Changes:**
* `FaviconDir` param is added to `skin.properties`. It is commented out by default. Only Network Edition users are allow to change favicon as same as logo image.
* The value of `FaviconDir` is set in `ZmSkin.hints.favicon.dir` as string. It will be 0-length string if `FaviconDir` is not defined in `skin.properties`.
* Update `ZmMailApp.prototype._setFavIcon` to use `skin.hints.favicon.dir` if it has been set.
Note:
The url is sanitized at `appendChild` in `Dwt.setFavIcon`.
> ZCS-12549: add ability to specify favicon directory in a skin

- WebRoot/js/zimbraMail/briefcase/view/ZmDetailListView.js
- WebRoot/js/zimbraMail/calendar/controller/ZmCalViewController.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalColView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalDayView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalListView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalMonthView.js
- WebRoot/js/zimbraMail/mail/view/ZmMailListView.js
- WebRoot/js/zimbraMail/share/controller/ZmListController.js
- WebRoot/js/zimbraMail/share/view/ZmListView.js
- WebRoot/js/zimbraMail/tasks/view/ZmTaskListView.js
**2.1.1_Not able to access the calendar with keyboard.docx**
> Fixed. Now user can navigate to each appointments appear on calendar view, work view block and can open quick add appointment dialog by pressing Enter key when focus is on work view block.
See the changes for MTS theme https://stash.corp.synacor.com/projects/ZIMBRA/repos/mail-client/pull-requests/337/overview
> ZCS-12655 WCAG | Classic UI | Medium Complexity | Keyboard issues Part - 4

- WebRoot/js/zimbraMail/calendar/view/ZmCalMonthView.js
- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
- WebRoot/js/zimbraMail/prefs/view/ZmPreferencesPage.js
- WebRoot/js/zimbraMail/prefs/view/ZmShortcutsPage.js
- WebRoot/skins/_base/base2/skin.html
- WebRoot/skins/_base/base3/skin.html
- WebRoot/templates/abook/Contacts.template
- WebRoot/templates/briefcase/Briefcase.template
- WebRoot/templates/mail/Message.template
- WebRoot/templates/share/Widgets.template
- WebRoot/templates/tasks/Tasks.template
**2.4.6_There are no heading throughout the Calendar Page.docx**
The sidebar of the calendar vertical has headings starting from level 2 and up to level 6 for nested folders.
The month view of Calendar Vertical has a level3 heading for the month name.
The title of the add event dialog is level3
**2.4.6_heading issue-Mail.docx**
The left sidebar all the headings have been defined by level based on their nesting level.
Considering only one level1 is required on a page, defined the top navigation of verticals as level2 headings.
the subject of the mail in the preview pane is level2 heading.
The contact name, briefcase file name, task name in the respective preview pane is assigned level3 heading.
**2.4.6_heading issue-Preferences.docx**
unnecessary headings defined for labels for preferences …
> ZCS- 12659: WCAG | Classic UI | Medium Complexity | Headings

- WebRoot/js/zimbraMail/calendar/view/ZmApptEditView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalItemEditView.js
- WebRoot/js/zimbraMail/calendar/view/ZmCalMonthView.js
- WebRoot/js/zimbraMail/mail/controller/ZmConvController.js
- WebRoot/js/zimbraMail/mail/controller/ZmMsgController.js
- WebRoot/js/zimbraMail/share/controller/ZmListController.js
- WebRoot/js/zimbraMail/share/view/ZmListView.js
- WebRoot/js/zimbraMail/share/view/ZmNavToolBar.js
- WebRoot/js/zimbraMail/tasks/view/ZmTaskEditView.js
Fixed element contrast and tab navigation related issues.
- On Add/Edit appointment dialog, included tinymce toolbar as part of keyboard tab navigation.
- On Add/Edit task dialog, Added all interactive elements as part of keyboard tab navigation.
- Calendar month view, Fixed tab navigation by including first's day block in the tab navigation when today's day block is not present in the current view.
- Message/Conversation view in the new tab, Fixed tab navigation. Previously, tab navigation get stuck on msg header block.
- Message/Conversation list view, Updated keyboard shortcut for opening context menu on header element.
> ZCS-12661 Fix classic client WCAG related issues

- WebRoot/public/login.jsp
**Enhancement:**
Add an ability to load a domain-specific login page without redirection for multi-tenant system.
`zimbraWebClientLoginURL` and `zimbraWebClientLogoutURL` cause redirection to the specified login/logout URL. There is a customer who doesn't want the redirection.
**Use case:**
For example, assuming
* `zimbraDomainLoginPageEnabled` is `TRUE`
* `zimbraDomainLoginPagePath` is `/custom/domain2-login.jsp`
* `zimbraDomainLoginPageFallbackPath` is `/custom/fallback.jsp`
* `zimbraDomainLoginPageErrorPath` is `/custom/error.jsp`
* the custom jsp files are deployed on `/opt/zimbra/jetty/webapps/zimbra/custom/` directory.
* a domain `domain2.dev.zimbra.com` exists. Its `zimbraVirtualHostname` is `vdomain2.dev.zimbra.com`.
In this case, when a user accesses a login page …
> ZCS-12712: added ability to load domain-specific login page without redirection

- WebRoot/h/changepass
Adding an ability to show additional explanation in change password page when `passwordExplanation` is defined in `ZhMsg.properties`.
> ZCS-12881: add ability to show explanation in change password page

- WebRoot/js/zimbraMail/calendar/view/ZmApptEditView.js
- WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
- WebRoot/js/zimbraMail/mail/view/prefs/ZmSignaturesPage.js
- WebRoot/js/zimbraMail/share/model/ZmSettings.js
- WebRoot/templates/prefs/Pages.template
Hide the following items when zimbraBlockEmailSendFromImapPop is TRUE.
* Compose -> From options -> external imap / pop accounts
* Calendar ->  From options -> external imap / pop accounts
* Preferences -> Signatures -> external imap / pop accounts
* Preferences -> Accounts -> external imap / pop account setting -> Settings for Sent Messages (From display name, Reply-to and Signature)
> ZCS-12836: Add ability to suppress sending a message from external email addresses

- WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
**Issues:**
Two issues are observed in Japanese language setting in Compose page.
1. Login to Classic UI
2. Configure preferences as follows.
Preferences -> Mail -> Composing Messages -> Choose "Compose As Text"
Preferences -> General -> Language -> Japanese
3. Reload the page (press F5 key)
4. Click "New Message"
5. Click Options -> Format as HTML
6. A script error dialog is shown (Issue 1)
7. Close the dialog and add any email address in To field.
8. Click Cancel. A confirmation dialog is shown.
9. `disabled` attribute is not added to `input` element of subject field. (Issue 2)
It should be added as follows.
```
<input type="text" id="zv__COMPOSE-1_subject_control" class="subjectField" autocomplete="off" aria-label="件名" disabled>
```
**Changes:**
* Issue 1: add a condition to `if` …
> ZCS-12599: fixed script error in Compose

- WebRoot/js/zimbraMail/abook/view/ZmEditContactView.js
- WebRoot/js/zimbraMail/share/ZmUploadManager.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmUploadDialog.js
**Problem:**
In Edit Contact page, user can upload photo image. The allowed image file types (extensions) are defined in the source code.
```
ZmEditContactViewImage.prototype._chooseImage = function() {
var dialog = appCtxt.getUploadDialog();
dialog.setAllowedExtensions(["png","jpg","jpeg","gif"]);
```
However, it does not work.
(A) Other images like BMP can be uploaded.
(B) Non-image file like PDF can be uploaded and then an error dialog is shown at rendering the image. The allowed extensions must be checked before a file is uploaded.
Regarding (B), an error dialog is shown as the screenshot.
The photo area flickers until the edit contact page is closed.
This is because, a file is uploaded to the server and then the browser tries to render it as an image. However, it is actually not an …
> ZCS-12600: activate allowed extensions for contact photo

- WebRoot/js/zimbraMail/abook/view/ZmContactPicker.js
- WebRoot/templates/abook/Contacts.template
**Issue:**
When zimbraFeatureSharingEnabled and zimbraFeatureGalEnabled are FALSE, the width of address picker dialog is narrow.
When they are FALSE, "Show names from: + Options" is not included in the dialog. It is not just invisible but html elements for the label and option does not exist. Then the width of the dialog decreases.
**Fix:**
* set the width of the dialog to `900px` when the "Show names from:" option does not exist
* modified a template
* When the option exists, it works as it is.
* When it does not exist, `td` element with `width='300px'` is used.
**Additional information:**
When the attributes are TRUE, the width of the dialog depends on the max string length of "Show name from" options.
For example, with the following options,
(English)
* Global Address …
> ZCS-12542: increase the width of address picker dialog when Sharing feature and GAL are disabled

- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
**Problems:**
There are two problems in external imap/pop account setting. `zimbraDataSourceEmailAddress` is not set in a data source object in both cases. It should always be set and unique for check of duplication and for sieve filter execution.
* ZCS-9175
* When the same email address is set in "Email address" and "Username of Account", `emailAddress` attribute is not set in CreateDetaSourceRequest. 
* ZBUG-1876
* When "Email address" field is empty, `emailAddress` attribute is not set in CreateDetaSourceRequest.
**Changes:**
* ZCS-9175
* Add the entered string to datasource object which is being edited
* ZBUG-1876
* Add empty check on Email address
* Generate an email address and set it to the list of accounts in Accounts section when it is empty.
> ZCS-9175, ZBUG-1876: validation of Email Address field in external account setting

- WebRoot/public/launchZCS.jsp
- WebRoot/public/login.jsp
**Issue:**
Looping access occurs when accessing Classic UI from PC with small resolution.
Steps to reproduce:
1. set account's zimbraPrefClientType to "advanced"
2. access Login page using a PC browser. The display resolution is less than 600x800 (width x height)
3. choose "Classic" client type and log in to the account. The URL has "client=advanced" parameter. (https://host/?client=advanced )
6. remove the parameter and access https://host/
7. Looping access occurs. The URL has "client=standard" parameter.
**Changes:**
* launchZCS.jsp: changed the parameter to `screenSize=small` for redirection to login.jsp
* login.jsp
* when parameter has `screenSize=small` and Modern UI is supported, set `client` to `modern`
* when parameter has `screenSize=small` and Modern UI is not supported, set …
> ZCS-13042: fixed for device with small screen resolution

- WebRoot/WEB-INF/tags/rest/restHead.tag
- WebRoot/WEB-INF/tags/rest/restView.tag
- WebRoot/h/rest
**Issue:**
* favicon is not shown in a calendar shown in a separate window. (right-click a calendar and click "Open in a separate window")
**Changes:**
* In `h/rest`, call `app:skin` first and then call `fmt:setBundle` after a skin is identified. All tag files called from here can use a right ZhMsg. If ZhMsg exists in a skin directory, it is used. If it does not exist, default ZhMsg is used.
* `app:skin` in `restView.tag` is no longer necessary.
> ZBUG-2691: set favicon in calendar shown in a separate window

- WebRoot/WEB-INF/tags/head.tag
- WebRoot/skins/_base/base3/print.css
- WebRoot/skins/bare/manifest.xml
- WebRoot/skins/beach/manifest.xml
- WebRoot/skins/bones/manifest.xml
- WebRoot/skins/carbon/manifest.xml
- WebRoot/skins/harmony/manifest.xml
- WebRoot/skins/hotrod/manifest.xml
- WebRoot/skins/lake/manifest.xml
- WebRoot/skins/lavender/manifest.xml
- WebRoot/skins/lemongrass/manifest.xml
- WebRoot/skins/oasis/manifest.xml
- WebRoot/skins/pebble/manifest.xml
- WebRoot/skins/sand/manifest.xml
- WebRoot/skins/serenity/manifest.xml
- WebRoot/skins/sky/manifest.xml
- WebRoot/skins/smoke/manifest.xml
- WebRoot/skins/steel/manifest.xml
- WebRoot/skins/tree/manifest.xml
- WebRoot/skins/twilight/manifest.xml
- WebRoot/skins/waves/manifest.xml
**Problem:**
css file in a skin directory is not loaded on print message/contact/appointment/task page.
**Changes:**
* `head.tag`
* specify `print` in `client` param for print page
* add `skin.css` for print page
* `WebRoot/skins/_base/base3/print.css`: add empty file. Administrator can add style(s) as necessary.
* `manifest.xml` in each skin directory
* add `<print>` element which contains the `print.css`
* add `<cssIgnore>` element not to include css files defined in `common / css` section.
* see https://github.com/Zimbra/zm-ajax/pull/116
* indentation: use tab space
* line break: use LF on all skins
FYI, you can ignore changes of indentation (white space / tab space) and line breaks (CRLF / LF) in code diff page.
File changed -> Gear icon -> Check "Hide whitespace" -> Click "Apply and …
> ZCS-12677: add ability to load css in a skin on print page

- WebRoot/js/zimbraMail/mail/model/ZmMailMsg.js
- Passing selected From account's email address in SendMessage request's header context
- Setting message's **did** as `<account identity>:<draft id>` When user sending message on behalf of account such that server delete the message's draft on message sent.
Automation coverage: https://github.com/ZimbraOS/zm-frontend-automation/pull/39
> ZBUG-3232 Sent mail doesn't appear in sent folder of send as address.

- Dockerfile
Removed some code from Dockerfile to keep Modern UI path as `/modern`.
> ZCS-13121: reverted part of ZCS-12886

- WebRoot/WEB-INF/web.xml
**Problem**
* localHost used by ZJspSession (for soap url) needs to be overridden by adding an override in web.xml.
* zok needs a method of overriding with a persisted config.
**Solution**
* Allow a non-empty value in localconfig to set the override, leaving this block commented out if localconfig key is empty.
Alternatively we can set it directly if a specific value is present in one of the fields used by zok (e.g. mls_service_endpoint).
> ZCS-13393 Support localHost config option for ZJspSession.

- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
- WebRoot/public/launchZCS.jsp
Product help pages will be excluded from next build and patch releases. Those can be include back by installing "zimbra-help" package. This code removes the "Product Help" link from the UI when the help pages are unavailable.
> ZCS-2733 remove product help page link if help pages are not available in the build

- WebRoot/js/zimbraMail/share/model/ZmSettings.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmFolderPropsDialog.js
When `zimbraFeatureRetentionPolicyEnabled` is disabled, the Retention tab present in the folder's edit properties option should be hidden.
Automation changes - https://github.com/ZimbraOS/zm-frontend-automation/pull/86
> ZCS-13590 remove retention policy setting if zimbraFeatureRetentionPolicyEnabled is disabled

- WebRoot/h/printcontacts
Add `derefGroupMember="true"` to `zm:getAllContacts` so that members of a contact group is shown in Print Contact page.
**Related PRs:**
* https://github.com/Zimbra/zm-mailbox/pull/1510
* https://github.com/Zimbra/zm-taglib/pull/49
> ZCS-13306: added derefGroupMember for print contacts

- WebRoot/js/zimbraMail/mail/view/ZmMailListView.js
**Issue:**
Checkbox becomes unchecked when a tag is added to/removed from a message or conversation.
It occurs with the following configuration:
* zimbraPrefReadingPaneLocation right, or
* zimbraPrefColorMessagesEnabled TRUE
`DwtListView.prototype.redrawItem` is called when a tag is added/removed and the configuration has been set as the above.
```
if ((!this.isMultiColumn() || appCtxt.get(ZmSetting.COLOR_MESSAGES))
&& (ev.event == ZmEvent.E_TAGS || ev.event == ZmEvent.E_REMOVE_ALL)) {
//...
this.redrawItem(item);
```
`redrawItem` resets the status of the checkbox of the target item. Then checkbox becomes unchecked.
**Fix:**
* add `restoreState` parameter to `DwtListView.prototype.redrawItem`
* https://github.com/Zimbra/zm-ajax/pull/126
* change to call `redrawItem` with …
> ZBUG-3437: restore checkbox status when tag is added or removed

- WebRoot/js/zimbraMail/share/model/ZmSearch.js
- In Search API sent parameter recip:3, in order to get CC and BCC data in response from BE to display the correct count above when the type is the message.
> ZCS-13852: Classic UI | Display mail recall option in context menu of mail

- WebRoot/js/zimbraMail/core/ZmRequestMgr.js
- WebRoot/js/zimbraMail/share/model/ZmSettings.js
Adding a function not to show a dialog of server version change when `zimbraServerVersionChangeNotificationDisabled` is TRUE.
Default value is FALSE - a dialog will be shown.
Related PR:
* https://github.com/Zimbra/zm-mailbox/pull/1549
> ZCS-14405: added a function not to show server version change notification dialog

- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmTwoFactorSetupDialog.js
**Issues:**
* when `zimbraFeatureResetPasswordStatus` is `enabled` or `suspended` on a domain and it is `disabled` on an account, user cannot configure recovery address in Password Recovery Account settings. The error message `Something went wrong. Please contact your administrator.` is shown.
* in the above case, when a user tries to configure 2FA email method, the user is asked to configure recovery address first. However, a recovery address cannot be configured. Then 2FA email method cannot be configured.
Settings passed via GetDomainInfo override account settings in the following code. A value of zimbraFeatureResetPasswordStatus in domain level is always used if it is not empty.
https://github.com/Zimbra/zm-web-client/blob/develop/WebRoot/js/zimbraMail/core/ZmZimbraMail …
> ZCS-14527: changed to show password recovery account settings based on account setting

- WebRoot/skins/_base/base3/skin.css
- WebRoot/skins/harmony/skin.css
Fixed done in below commit is applicable to all the themes and not limited to harmony only
https://github.com/Zimbra/zm-web-client/commit/ce7ac70f45d5258b4212dceb76d1a2f467825be4
> ZBUG-3877: Corp Email: Text Alignment Issues in latest Firefox version

- WebRoot/js/zimbraMail/package/TwoFactor.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmTwoFactorSetupDialog.js
Adding email address format check at 2FA email method setup. `Next` button is disabled until an email address in valid format is entered.
An existing function `AjxEmailAddress.isValid` is used for the check. `TwoFactor.js` is updated so that `AjxEmailAddress.js` is loaded in 2FA mandatory setup page, which is shown after login with username and password when zimbraFeatureTwoFactorAuthRequired is TRUE.
> ZCS-14526: added email address format check for 2FA email method setup

- WebRoot/js/zimbraMail/mail/view/prefs/ZmAccountsPage.js
- WebRoot/js/zimbraMail/share/view/dialog/ZmTwoFactorSetupDialog.js
**Issue:**
No error message is shown when disabling a 2FA method (app or email) fails.
For example, when a single 2FA method is enabled, zimbraFeatureTwoFactorAuthRequired is changed from FALSE to TRUE by administrator after the user logs in to web client and the user tries to disable the 2FA method, it fails because 2FA is mandatory. An error is returned from a server, but UI does not show any message.
**Changes:**
* updated `ZmTwoFactorSetupDialog.disableTwoFactorAuthCallback` to show an error message.
* Note: it is called via `ZmTwoFactorSetupDialog.disableTwoFactorAuth` and `ZmAccountsPage.prototype._recoveryResetRequest`. For the latter, 2nd param `dialog` is null and 4th `result` is empty (undefined). `result` does not need to be checked.
* set a title in some dialogs. Previously …
> ZCS-14513: added error handling when disabling 2FA fails

- WebRoot/js/zimbraMail/prefs/view/ZmFilterRuleDialog.js
**Issue in current implementation:** 
Date Filter in Advance setting displays incorrect date if selected date is appended with current time.
**what is observed:**
Current date gets appended to the selected date and its equivalent timeStamp is calculated and sent to API. Since current time is appended it displays incorrect date when server timezone and client timezone varies and it dose not handle DST time. 
**What should it be changed to:**
Removing the time part and sending only date part in long format to the API.
**Example:**
If the selected date is 1/1/2024 then its equivalent timestamp value 1704090386 is sent to ModifyFilterRulesRequest.
Whose equivalent date value is Monday, 1 January 2024 01:26:26 [GMT-05:00]
But in response we get 1704067200. i.e, Sunday, 31 December 2023 …
> PREAPPS-7606: Date Filter in Advance setting displays incorrect date if selected date is appended with current time.

- WebRoot/public/login.jsp
- 'Classic' and 'Modern' options are displayed in the client dropdown menu of the login page, depending on the values of `zimbraClassicWebClientDisabled` and `zimbraModernWebClientDisabled` respectively.
- After successful login: 
1.  Redirecting user to the Classic or Modern client based on `zimbraClassicWebClientDisabled` and `zimbraModernWebClientDisabled` value. 
2. Preventing user to access Classic UI if `zimbraClassicWebClientDisabled` is TRUE by selecting 'Classic' client option on the login screen and accessing the classic UI client via a URL like `?client=advanced`.
3. The user will be redirected to the Classic UI if they have selected the '**Classic**' option on the login page or if they are accessing the Classic UI client via a URL such as `?client=advanced` when …
> ZCS-14933: Prevent access of classic ui when zimbraClassicWebClientDisabled is TRUE

- WebRoot/css/zm.css
- WebRoot/js/zimbraMail/share/view/dialog/ZmTwoFactorSetupDialog.js
- WebRoot/templates/share/Dialogs.template
**Issue:**
Contents of the following page overlaps in a specific language and font:
2FA email setup > Enter a verification code
**Fix:**
Update the template and styles.
> ZCS-14601: fixed styles in 2FA code verification page

- WebRoot/js/zimbraMail/mail/controller/ZmConvController.js
- WebRoot/js/zimbraMail/mail/controller/ZmConvListController.js
**Issue:**
An error message is shown in the following case:
1. set Conversation view
2. receive an email with attachment
3. show the message and click Reply
4. edit message body, click "Add attachments from original message" and click "Save Draft"
5. close the tab to go back to conversation list
6. check that the conversation has the received message and the draft
7. double-click the conversation. It is shown in another tab.
8. click Reply
9. edit message body and click Save Draft
10. click "Add attachments from original message" and click "Save Draft"
11. SaveDraftRequest fails and then an error message is shown
**Analysis:**
In step 9, the reply message is created based on the draft. 
On the other hand, not double-click but just click the conversation in step 7 (i.e. stay in Mail tab) …
> ZCS-14872: changed to pass params to get a message in Conv view

- WebRoot/js/zimbraMail/mail/controller/ZmComposeController.js
**Issue:** An error message is displayed in the following scenario:
Steps to reproduce the issue:
1. Compose an email.
2. Select a few attachment files. While the attachments are being uploaded, write something in the email Body.
3. While the attachment upload is still in progress, cancel the composed message.
4. After waiting for a few minutes, "mail.NO_SUCH_MSG" errors continue to occur in the web-client.
**Fix:** Resolve it by setting the _cancelAutoSaveDraft flag to true upon cancellation. Upon completion of the upload, check if the flag is true. If true, do not trigger the save draft request; otherwise, trigger it.
> ZBUG-3715 "No such message" error when clicking Cancel during attachment upload.

- WebRoot/public/login.jsp
**RCA**: Somewhere username is getting encoded when sending auth request, most probably the username which is being provided by the username is getting encoded using escapeXml and the trimmedUsername is used to validate the password rules which is also in an encoded form.
**Solution**: encoded form of trimmedUsername is stored in encodedUserName and the password is stored in encodedPwd 
which is being used to validate the zimbraFeatureAllowUsernameInPassword rule. Removed the escapeXml of JSTL from the trimmedUsername. It will send the unencoded data to hit the API.
> ZBUG-3617: User with & in username is unable to login to webmail

- WebRoot/js/zimbraMail/core/ZmAppCtxt.js
- WebRoot/js/zimbraMail/core/ZmAppViewMgr.js
- WebRoot/js/zimbraMail/core/ZmZimbraMail.js
- WebRoot/js/zimbraMail/mail/ZmMailApp.js
- WebRoot/js/zimbraMail/mail/controller/ZmComposeController.js
- WebRoot/js/zimbraMail/mail/controller/ZmConvListController.js
**Issue:**
* The same draft message could be shown in different tabs or separate windows. It caused an issue around SaveDraftRequest when the draft was sent on one of the tabs/windows but another was still opened.
* When Reply button was clicked, the replying message was shown in a tab. Then Reply, or Edit as New button was clicked on the same message, the existing tab was overwritten.
**Fix:**
Adding the following processes:
* Add a saved draft item to a compose controller so that the id of the draft message shown in a compose tab can be identified.
* Set a window name based on a message id when a window is shown or a draft is saved on the window.
* Check if the draft has already be shown in a tab or window when Edit action is executed on a draft.
* Call SaveDraftRequest before detaching …
> ZBUG-2856, ZBUG-4052: fixed tab and window control at compose

- WebRoot/js/zimbraMail/mail/view/ZmComposeView.js
**Issue:**
An inline image is not included in a reply/forward message when the sender of the original message is added to trusted address.
Source of an image was fetched in the following priority:
dfsrc => data-mce-src => src
Before the fix, `data-mce-src` is set for an image in a signature.
`<img pnsrc="cid:edf162835aead51e0a185735d5add806ee0b8710@zimbra" data-mce-src="https://HOST/home/ACCOUNT/Briefcase/imageg.png" src="https://HOST/service/home/~/?auth=co&amp;loc=en_US&amp;id=400&amp;part=2.2">`
At reply/forward, the url in `data-mce-src` is set in `src` of `img` tag when a trusted address is configured.
```
ZmComposeView.js, line 1239:
else if (showImages) {
var src = dfsrc;//x + "&t=" + (new Date()).getTime();
num++;
images[i].src = src; …
```
> ZBUG-3629: fixed handling of image in signature
